/* STUNIR Generated Code
 * Generated by: stunir_ir_to_code_spark v0.2.0
 * Module: mavlink_handler
 */

#include <stdint.h>
#include <stdbool.h>

int32_t parse_heartbeat(uint8_t* buffer, uint8_t len) {
    /* TODO: Implement */
    return 0;
}

int32_t send_heartbeat(uint8_t sys_id, uint8_t comp_id) {
    /* TODO: Implement */
    return 0;
}

