// Generated by STUNIR IR to Code Bridge
// Target: Rust


pub fn stop_execution(i32 sig) -> () {
    // TODO: Implement function body
    todo!()
}

pub fn execute() -> () {
    // TODO: Implement function body
    todo!()
}

pub fn prog_char() -> i32 {
    // TODO: Implement function body
    todo!()
}

pub fn input_char() -> i32 {
    // TODO: Implement function body
    todo!()
}

pub fn push_b10_const(*mut program_counter progctr) -> () {
    // TODO: Implement function body
    todo!()
}

pub fn assign(u8 code) -> () {
    // TODO: Implement function body
    todo!()
}
