// Generated by STUNIR IR to Code Bridge
// Target: Kotlin


fun stop_execution(Int sig): Unit {
    // TODO: Implement function body
}

fun execute(): Unit {
    // TODO: Implement function body
}

fun prog_char(): Int {
    // TODO: Implement function body
}

fun input_char(): Int {
    // TODO: Implement function body
}

fun push_b10_const(program_counter * progctr): Unit {
    // TODO: Implement function body
}

fun assign(Char code): Unit {
    // TODO: Implement function body
}
