#include <stdint.h>
#include <stdbool.h>

// Generated by STUNIR IR to Code Bridge
// Target: C


void stop_execution(int sig) {
    // TODO: Implement function body
}

void execute() {
    // TODO: Implement function body
}

int prog_char() {
    // TODO: Implement function body
}

int input_char() {
    // TODO: Implement function body
}

void push_b10_const(program_counter * progctr) {
    // TODO: Implement function body
}

void assign(char code) {
    // TODO: Implement function body
}
