// Generated by STUNIR IR to Code Bridge
// Target: Swift

import Foundation


func stop_execution(Int sig) -> Void {
    // TODO: Implement function body
}

func execute() -> Void {
    // TODO: Implement function body
}

func prog_char() -> Int {
    // TODO: Implement function body
}

func input_char() -> Int {
    // TODO: Implement function body
}

func push_b10_const(program_counter * progctr) -> Void {
    // TODO: Implement function body
}

func assign(Character code) -> Void {
    // TODO: Implement function body
}
