// Generated by STUNIR IR to Code Bridge
// Target: Go

package main


func stop_execution(sig int)  {
    // TODO: Implement function body
}

func execute()  {
    // TODO: Implement function body
}

func prog_char() int {
    // TODO: Implement function body
}

func input_char() int {
    // TODO: Implement function body
}

func push_b10_const(progctr *program_counter)  {
    // TODO: Implement function body
}

func assign(code byte)  {
    // TODO: Implement function body
}
