// Generated by STUNIR IR to Code Bridge
// Target: Java

public class Generated {{

    public static void stop_execution(int sig) {
        // TODO: Implement function body
    }

    public static void execute() {
        // TODO: Implement function body
    }

    public static int prog_char() {
        // TODO: Implement function body
    }

    public static int input_char() {
        // TODO: Implement function body
    }

    public static void push_b10_const(program_counter * progctr) {
        // TODO: Implement function body
    }

    public static void assign(char code) {
        // TODO: Implement function body
    }

}