// STUNIR Generated Code
// Generated by: stunir_ir_to_code_spark v0.7.1

double area(Shape shape) {
    /* TODO: Implement */
    return 0.0;
}

double perimeter(Shape shape) {
    /* TODO: Implement */
    return 0.0;
}

Shape scale(Shape shape, double factor) {
    /* TODO: Implement */
    return 0;
}

int32_t add(int32_t a, int32_t b) {
  /* UNKNOWN OP: noop */
  return 0;
}

int32_t multiply(int32_t x, int32_t y) {
  /* UNKNOWN OP: noop */
  return 0;
}

double distance(Point p1, Point p2) {
    /* TODO: Implement */
    return 0.0;
}

