#!/usr/bin/env python3
"""STUNIR Generated Code
Generated by: stunir_ir_to_code_spark v0.7.1
Module: name
"""

def area(shape: Shape) -> f64:
    pass  # TODO: Implement

def perimeter(shape: Shape) -> f64:
    pass  # TODO: Implement

def scale(shape: Shape, factor: f64) -> Shape:
    pass  # TODO: Implement

def add(a: i32, b: i32) -> i32:
    pass  # TODO: Implement

def multiply(x: i32, y: i32) -> i32:
    pass  # TODO: Implement

def distance(p1: Point, p2: Point) -> f64:
    pass  # TODO: Implement

