--  STUNIR Assembly Emitter - Ada SPARK Specification
--  Assembly code emitter
--  DO-178C Level A compliant
--  Generated by: STUNIR Emitter Generator v1.0
--  Timestamp: 2026-02-04T12:17:43.046275Z

pragma SPARK_Mode (On);

with Emitter_Types; use Emitter_Types;

package Assembly_Emitter is

   --  Assembly target configuration
   type Assembly_Config is record
      Syntax : String;
      Use_Att_Syntax : Boolean;
   end record;

   --  Default configuration
   Default_Config : constant Assembly_Config := (
      Syntax => intel,
      Use_Att_Syntax => False
   );

   --  Main emission procedure with SPARK contracts
   procedure Emit_Module (
      Name      : in Identifier_String;
      Content   : out Content_String;
      Config    : in Assembly_Config;
      Status    : out Emitter_Status)
      with Pre => Identifier_Strings.Length (Name) > 0,
           Post => (Status = Success) = (Content_Strings.Length (Content) > 0);

   --  Emit function code
   procedure Emit_Function (
      Func_Name : in Identifier_String;
      Params    : in String;
      Body_Code : in String;
      Content   : out Content_String;
      Status    : out Emitter_Status)
      with Pre => Identifier_Strings.Length (Func_Name) > 0;

   --  Type mapping from IR to Assembly
   function Map_Type_To_ASSEMBLY (IR_Type : IR_Data_Type) return Type_Name_String;

end Assembly_Emitter;
