/* STUNIR Generated Code
 * Generated by: stunir_ir_to_code_spark v0.7.1
 * Module: generics_test
 */

#include <stdint.h>
#include <stdbool.h>

void add_generic(void) {
    /* TODO: Implement */
    return;
}

void cast_and_add(void) {
    /* TODO: Implement */
    return;
}

void use_generic_add(void) {
    /* TODO: Implement */
    return;
}

