--  STUNIR Prolog Emitter - Ada SPARK Specification
--  Prolog logic programming emitter with support for multiple dialects
--  DO-178C Level A compliant
--  Generated by: STUNIR Emitter Generator v1.0
--  Timestamp: 2026-01-31T02:44:10.040252Z

pragma SPARK_Mode (On);

with Emitter_Types; use Emitter_Types;

package Prolog_Emitter is

   --  Prolog target configuration
   type Prolog_Config is record
      Dialect : String;
      Use_Modules : Boolean;
      Use_Constraints : Boolean;
      Use_Tabling : Boolean;
   end record;

   --  Default configuration
   Default_Config : constant Prolog_Config := (
      Dialect => swi_prolog,
      Use_Modules => True,
      Use_Constraints => False,
      Use_Tabling => False
   );

   --  Main emission procedure with SPARK contracts
   procedure Emit_Module (
      Name      : in Identifier_String;
      Content   : out Content_String;
      Config    : in Prolog_Config;
      Status    : out Emitter_Status)
      with Pre => Identifier_Strings.Length (Name) > 0,
           Post => (Status = Success) = (Content_Strings.Length (Content) > 0);

   --  Emit function code
   procedure Emit_Function (
      Func_Name : in Identifier_String;
      Params    : in String;
      Body_Code : in String;
      Content   : out Content_String;
      Status    : out Emitter_Status)
      with Pre => Identifier_Strings.Length (Func_Name) > 0;

   --  Type mapping from IR to Prolog
   function Map_Type_To_PROLOG (IR_Type : IR_Data_Type) return Type_Name_String;

end Prolog_Emitter;
