{-# LANGUAGE OverloadedStrings #-}

-- | Lexer code emitter
--
-- Lexer/tokenizer generator for multiple languages
--
-- Generated by: STUNIR Emitter Generator v1.0
-- Timestamp: 2026-01-31T02:44:18.376788Z
module STUNIR.Emitters.Lexer
  ( emitLexer
  , LexerConfig(..)
  ) where

import Data.Text (Text)
import qualified Data.Text as T
import STUNIR.Emitters.Types

-- | Lexer configuration
data LexerConfig = LexerConfig
  { configIndent :: Int
  , configValidate :: Bool
  } deriving (Show, Eq)

-- | Default configuration
defaultLexerConfig :: LexerConfig
defaultLexerConfig = LexerConfig
  { configIndent = 2
  , configValidate = True
  }

-- | Map IR type to Lexer type
mapIRType :: Text -> Text
mapIRType "i32" = "int32"
mapIRType "i64" = "int64"
mapIRType "f32" = "float"
mapIRType "f64" = "double"
mapIRType "bool" = "boolean"
mapIRType "string" = "string"
mapIRType _ = "int32"

-- | Emit function code
emitFunction :: Text -> Text -> Text -> Text
emitFunction funcName params body = T.unlines
  [ "function " <> funcName <> "(" <> params <> ") {"
  , body
  , "}"
  ]

-- | Emit Lexer module
emitLexer :: Text -> LexerConfig -> EmitterResult Text
emitLexer moduleName config = Right $ T.unlines $
  [ "/* STUNIR Generated Lexer Code */"
  , "/* Module: " <> moduleName <> " */"
  , "/* Generator: Haskell Pipeline */"
  , ""
  ] ++ moduleBody
  where
    moduleBody =
      [ "// Lexer implementation goes here"
      ]
