# Generated by STUNIR Code Emitter
# DO NOT EDIT MANUALLY

def main(a):
    # // step: assign target=b value=a
    # // step: call target=c value=add(b, 1)
    # // step: return value=c
    b = a
    c = add(b, 1)
    return c


