--  STUNIR Json Emitter - Ada SPARK Specification
--  JSON serialization and deserialization emitter
--  DO-178C Level A compliant
--  Generated by: STUNIR Emitter Generator v1.0
--  Timestamp: 2026-01-31T02:35:20.939899Z

pragma SPARK_Mode (On);

with Emitter_Types; use Emitter_Types;

package Json_Emitter is

   --  Json target configuration
   type Json_Config is record
      Indent_Width : Positive range 2 .. 8;
      Use_Schema : Boolean;
      Validate_Output : Boolean;
      Compact_Mode : Boolean;
   end record;

   --  Default configuration
   Default_Config : constant Json_Config := (
      Indent_Width => 2,
      Use_Schema => False,
      Validate_Output => True,
      Compact_Mode => False
   );

   --  Main emission procedure with SPARK contracts
   procedure Emit_Module (
      Name      : in Identifier_String;
      Content   : out Content_String;
      Config    : in Json_Config;
      Status    : out Emitter_Status)
      with Pre => Identifier_Strings.Length (Name) > 0,
           Post => (Status = Success) = (Content_Strings.Length (Content) > 0);

   --  Emit function code
   procedure Emit_Function (
      Func_Name : in Identifier_String;
      Params    : in String;
      Body_Code : in String;
      Content   : out Content_String;
      Status    : out Emitter_Status)
      with Pre => Identifier_Strings.Length (Func_Name) > 0;

   --  Type mapping from IR to Json
   function Map_Type_To_JSON (IR_Type : IR_Data_Type) return Type_Name_String;

end Json_Emitter;
