--  STUNIR Lexer Emitter - Ada SPARK Specification
--  Lexer/tokenizer generator for multiple languages
--  DO-178C Level A compliant
--  Generated by: STUNIR Emitter Generator v1.0
--  Timestamp: 2026-01-31T02:44:18.376788Z

pragma SPARK_Mode (On);

with Emitter_Types; use Emitter_Types;

package Lexer_Emitter is

   --  Lexer target configuration
   type Lexer_Config is record
      Target_Language : String;
      Use_Regex : Boolean;
      Track_Positions : Boolean;
   end record;

   --  Default configuration
   Default_Config : constant Lexer_Config := (
      Target_Language => python,
      Use_Regex => True,
      Track_Positions => True
   );

   --  Main emission procedure with SPARK contracts
   procedure Emit_Module (
      Name      : in Identifier_String;
      Content   : out Content_String;
      Config    : in Lexer_Config;
      Status    : out Emitter_Status)
      with Pre => Identifier_Strings.Length (Name) > 0,
           Post => (Status = Success) = (Content_Strings.Length (Content) > 0);

   --  Emit function code
   procedure Emit_Function (
      Func_Name : in Identifier_String;
      Params    : in String;
      Body_Code : in String;
      Content   : out Content_String;
      Status    : out Emitter_Status)
      with Pre => Identifier_Strings.Length (Func_Name) > 0;

   --  Type mapping from IR to Lexer
   function Map_Type_To_LEXER (IR_Type : IR_Data_Type) return Type_Name_String;

end Lexer_Emitter;
