/* STUNIR Generated Code
 * Generated by: stunir_ir_to_code_spark v0.7.1
 * Module: nested_3_levels
 */

#include <stdint.h>
#include <stdbool.h>

int32_t test_nested_3(int32_t x) {
  if (x > 0) {
    if (x > 10) {
      if (x > 20) {
  return 200;
  return 100;
      } else {
  return 100;
      }
    } else {
  return 100;
    }
  return 10;
  } else {
  return 100;
  return 10;
  }
  return 0;
}

