/* STUNIR Generated Code
 * Generated by: stunir_ir_to_code_spark v0.2.0
 * Module: control_flow_test
 */

#include <stdint.h>
#include <stdbool.h>

int32_t test_if_else(int32_t x) {
  if (x > 0) {
    /* then block - nested control flow support limited */
  }
  return 0;
}

int32_t test_while_loop(int32_t n) {
  uint8_t sum = 0;
  uint8_t i = 0;
  while (i < n) {
    /* loop body - nested control flow support limited */
  }
  return sum;

}

int32_t test_for_loop(int32_t n) {
  uint8_t sum = 0;
  for (int i = 0; i < n; i++) {
    /* loop body - nested control flow support limited */
  }
  return sum;

}

int32_t test_nested_if(int32_t x, int32_t y) {
  if (x > 0) {
    /* then block - nested control flow support limited */
  }
  return 0;
}

int32_t test_if_without_else(int32_t x) {
  uint8_t result = 0;
  if (x > 10) {
    /* then block - nested control flow support limited */
  }
  return result;

}

