--  STUNIR Asp Emitter - Ada SPARK Specification
--  Answer Set Programming emitter (Clingo, DLV, ASP-Core-2)
--  DO-178C Level A compliant
--  Generated by: STUNIR Emitter Generator v1.0
--  Timestamp: 2026-01-31T02:44:19.574295Z

pragma SPARK_Mode (On);

with Emitter_Types; use Emitter_Types;

package Asp_Emitter is

   --  Asp target configuration
   type Asp_Config is record
      Solver : String;
      Use_Optimization : Boolean;
      Use_Choice_Rules : Boolean;
   end record;

   --  Default configuration
   Default_Config : constant Asp_Config := (
      Solver => clingo,
      Use_Optimization => True,
      Use_Choice_Rules => True
   );

   --  Main emission procedure with SPARK contracts
   procedure Emit_Module (
      Name      : in Identifier_String;
      Content   : out Content_String;
      Config    : in Asp_Config;
      Status    : out Emitter_Status)
      with Pre => Identifier_Strings.Length (Name) > 0,
           Post => (Status = Success) = (Content_Strings.Length (Content) > 0);

   --  Emit function code
   procedure Emit_Function (
      Func_Name : in Identifier_String;
      Params    : in String;
      Body_Code : in String;
      Content   : out Content_String;
      Status    : out Emitter_Status)
      with Pre => Identifier_Strings.Length (Func_Name) > 0;

   --  Type mapping from IR to Asp
   function Map_Type_To_ASP (IR_Type : IR_Data_Type) return Type_Name_String;

end Asp_Emitter;
