--  Test for Asp Emitter
--  Generated by: STUNIR Emitter Generator v1.0

with Ada.Text_IO;
with Asp_Emitter; use Asp_Emitter;
with Emitter_Types; use Emitter_Types;

procedure Test_Asp_Emitter is
   Config  : Asp_Config := Default_Config;
   Content : Content_String;
   Status  : Emitter_Status;
   Name    : Identifier_String;
begin
   Ada.Text_IO.Put_Line ("Testing Asp Emitter...");
   
   Name := Identifier_Strings.To_Bounded_String ("test_module");
   
   Emit_Module (Name, Content, Config, Status);
   
   if Status = Success then
      Ada.Text_IO.Put_Line ("✅ Test PASSED");
      Ada.Text_IO.Put_Line ("Generated code:");
      Ada.Text_IO.Put_Line (Content_Strings.To_String (Content));
   else
      Ada.Text_IO.Put_Line ("❌ Test FAILED");
   end if;
end Test_Asp_Emitter;
