{-# LANGUAGE OverloadedStrings #-}
module STUNIR.SemanticIR.Emitters.Specialized.Bytecode
  ( BytecodeEmitter, BytecodeConfig(..)
  , defaultBytecodeConfig, emitBytecode
  ) where

import Data.Text (Text)
import qualified Data.Text as T
import STUNIR.SemanticIR.Emitters.Base
import STUNIR.SemanticIR.Emitters.Types

data BytecodeConfig = BytecodeConfig
  { bytecodeBaseConfig :: !EmitterConfig
  } deriving (Show)

defaultBytecodeConfig :: FilePath -> Text -> BytecodeConfig
defaultBytecodeConfig outputDir moduleName = BytecodeConfig
  { bytecodeBaseConfig = defaultEmitterConfig outputDir moduleName
  }

data BytecodeEmitter = BytecodeEmitter BytecodeConfig

instance Emitter BytecodeEmitter where
  emit (BytecodeEmitter config) irModule
    | not (validateIR irModule) = Left "Invalid IR module"
    | otherwise = Right $ EmitterResult Success [mainFile] (gfSize mainFile) Nothing
    where mainFile = GeneratedFile (T.unpack $ imModuleName irModule <> ".txt")
                                    (computeFileHash content) (T.length content)
          content = T.unlines ["-- STUNIR Generated Bytecode Code", "-- Module: " <> imModuleName irModule]

emitBytecode :: IRModule -> FilePath -> Either Text EmitterResult
emitBytecode irModule outputDir =
  emit (BytecodeEmitter $ defaultBytecodeConfig outputDir (imModuleName irModule)) irModule
