{-# LANGUAGE OverloadedStrings #-}

-- | AsmIr code emitter
--
-- Assembly IR emitter (LLVM IR, custom IR formats)
--
-- Generated by: STUNIR Emitter Generator v1.0
-- Timestamp: 2026-01-31T02:44:19.170633Z
module STUNIR.Emitters.AsmIr
  ( emitAsmIr
  , AsmIrConfig(..)
  ) where

import Data.Text (Text)
import qualified Data.Text as T
import STUNIR.Emitters.Types

-- | AsmIr configuration
data AsmIrConfig = AsmIrConfig
  { configIndent :: Int
  , configValidate :: Bool
  } deriving (Show, Eq)

-- | Default configuration
defaultAsmIrConfig :: AsmIrConfig
defaultAsmIrConfig = AsmIrConfig
  { configIndent = 2
  , configValidate = True
  }

-- | Map IR type to AsmIr type
mapIRType :: Text -> Text
mapIRType "i32" = "int32"
mapIRType "i64" = "int64"
mapIRType "f32" = "float"
mapIRType "f64" = "double"
mapIRType "bool" = "boolean"
mapIRType "string" = "string"
mapIRType _ = "int32"

-- | Emit function code
emitFunction :: Text -> Text -> Text -> Text
emitFunction funcName params body = T.unlines
  [ "function " <> funcName <> "(" <> params <> ") {"
  , body
  , "}"
  ]

-- | Emit AsmIr module
emitAsmIr :: Text -> AsmIrConfig -> EmitterResult Text
emitAsmIr moduleName config = Right $ T.unlines $
  [ "/* STUNIR Generated AsmIr Code */"
  , "/* Module: " <> moduleName <> " */"
  , "/* Generator: Haskell Pipeline */"
  , ""
  ] ++ moduleBody
  where
    moduleBody =
      [ "// Asm_Ir implementation goes here"
      ]
