{-# LANGUAGE OverloadedStrings #-}

-- | Planning code emitter
--
-- AI planning language emitter (PDDL, STRIPS, HTN)
--
-- Generated by: STUNIR Emitter Generator v1.0
-- Timestamp: 2026-01-31T02:44:18.781168Z
module STUNIR.Emitters.Planning
  ( emitPlanning
  , PlanningConfig(..)
  ) where

import Data.Text (Text)
import qualified Data.Text as T
import STUNIR.Emitters.Types

-- | Planning configuration
data PlanningConfig = PlanningConfig
  { configIndent :: Int
  , configValidate :: Bool
  } deriving (Show, Eq)

-- | Default configuration
defaultPlanningConfig :: PlanningConfig
defaultPlanningConfig = PlanningConfig
  { configIndent = 2
  , configValidate = True
  }

-- | Map IR type to Planning type
mapIRType :: Text -> Text
mapIRType "i32" = "int32"
mapIRType "i64" = "int64"
mapIRType "f32" = "float"
mapIRType "f64" = "double"
mapIRType "bool" = "boolean"
mapIRType "string" = "string"
mapIRType _ = "int32"

-- | Emit function code
emitFunction :: Text -> Text -> Text -> Text
emitFunction funcName params body = T.unlines
  [ "function " <> funcName <> "(" <> params <> ") {"
  , body
  , "}"
  ]

-- | Emit Planning module
emitPlanning :: Text -> PlanningConfig -> EmitterResult Text
emitPlanning moduleName config = Right $ T.unlines $
  [ "/* STUNIR Generated Planning Code */"
  , "/* Module: " <> moduleName <> " */"
  , "/* Generator: Haskell Pipeline */"
  , ""
  ] ++ moduleBody
  where
    moduleBody =
      [ "// Planning implementation goes here"
      ]
