{-# LANGUAGE OverloadedStrings #-}

-- | Systems code emitter
--
-- Systems programming emitter (C, C++, Rust, Zig, Ada)
--
-- Generated by: STUNIR Emitter Generator v1.0
-- Timestamp: 2026-01-31T02:44:18.974822Z
module STUNIR.Emitters.Systems
  ( emitSystems
  , SystemsConfig(..)
  ) where

import Data.Text (Text)
import qualified Data.Text as T
import STUNIR.Emitters.Types

-- | Systems configuration
data SystemsConfig = SystemsConfig
  { configIndent :: Int
  , configValidate :: Bool
  } deriving (Show, Eq)

-- | Default configuration
defaultSystemsConfig :: SystemsConfig
defaultSystemsConfig = SystemsConfig
  { configIndent = 2
  , configValidate = True
  }

-- | Map IR type to Systems type
mapIRType :: Text -> Text
mapIRType "i32" = "int32"
mapIRType "i64" = "int64"
mapIRType "f32" = "float"
mapIRType "f64" = "double"
mapIRType "bool" = "boolean"
mapIRType "string" = "string"
mapIRType _ = "int32"

-- | Emit function code
emitFunction :: Text -> Text -> Text -> Text
emitFunction funcName params body = T.unlines
  [ "function " <> funcName <> "(" <> params <> ") {"
  , body
  , "}"
  ]

-- | Emit Systems module
emitSystems :: Text -> SystemsConfig -> EmitterResult Text
emitSystems moduleName config = Right $ T.unlines $
  [ "/* STUNIR Generated Systems Code */"
  , "/* Module: " <> moduleName <> " */"
  , "/* Generator: Haskell Pipeline */"
  , ""
  ] ++ moduleBody
  where
    moduleBody =
      [ "// Systems implementation goes here"
      ]
