/* STUNIR Generated Code
 * Generated by: stunir_ir_to_code_spark v0.2.0
 * Module: mavlink_handler
 */

#include <stdint.h>
#include <stdbool.h>

int32_t buffer(uint8_t* buffer, uint8_t len) {
  int32_t msg_type = buffer[0];
  uint8_t result = 0;
  return result;

}

int32_t sys_id(uint8_t sys_id, uint8_t comp_id) {
  uint8_t status = 1;
  return status;

}

int32_t port(uint16_t port) {
  int32_t connection_fd = -1;
  /* nop */
  return connection_fd;

}

bool sysid(uint8_t sysid, uint8_t compid) {
  bool success = false;
  /* nop */
  return success;

}

bool sysid(uint8_t sysid, uint8_t compid) {
  bool success = false;
  return success;

}

bool sysid(uint8_t sysid, uint8_t mode) {
  bool result = false;
  return result;

}

bool sysid(uint8_t sysid, int32_t altitude) {
  bool success = false;
  return success;

}

bool sysid(uint8_t sysid) {
  bool success = false;
  return success;

}

Position sysid(uint8_t sysid) {
  uint8_t pos_lat = 0;
  uint8_t pos_lon = 0;
  uint8_t pos_alt = 0;
  return Position{pos_lat, pos_lon, pos_alt};

}

uint8_t sysid(uint8_t sysid) {
  uint8_t battery_pct = 100;
  return battery_pct;

}

int32_t sysid(uint8_t sysid, uint8_t compid) {
  uint8_t status = 0;
  return status;

}

