/* STUNIR Generated Code
 * Generated by: stunir_ir_to_code_spark v0.7.1
 * Module: break_while_test
 */

#include <stdint.h>
#include <stdbool.h>

int32_t find_first_divisible(int32_t max, int32_t divisor) {
  uint8_t i = 1;
  int32_t result = -1;
  while (i < max) {
    if (i % divisor == 0) {
  int32_t result = i;
      break;
    }
  int32_t i = i + 1;
  }
  return result;

}

