#!/usr/bin/env python3
"""Emit deterministic SMT-LIB v2 (SMT2) artifacts from the IR manifest.

v0 semantics: introspection/stub.
The emitted SMT2 is intentionally minimal and deterministic.
"""

import argparse
import hashlib
import json
from pathlib import Path


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open('rb') as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b''):
            h.update(chunk)
    return h.hexdigest()


def load_ir_manifest(path: Path) -> dict:
    obj = json.loads(path.read_text(encoding='utf-8'))
    if not isinstance(obj, dict) or obj.get('schema') not in ('stunir.ir_manifest.v2',):
        raise SystemExit(f'Unexpected IR manifest schema in {path}: {obj.get("schema")!r}')
    return obj


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding='utf-8', newline='\n')


def gen_problem(ir_manifest_sha: str, nfiles: int) -> str:
    return f"""; Generated by STUNIR (SMT2 backend, v0)
; IR manifest sha256: {ir_manifest_sha}
; IR files: {nfiles}

(set-logic QF_UF)
(declare-fun a () Bool)
(assert a)
(check-sat)
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument('--variant', required=True, choices=['portable', 'z3'])
    ap.add_argument('--ir-manifest', required=True)
    ap.add_argument('--out-root', required=True)
    args = ap.parse_args()

    ir_manifest_path = Path(args.ir_manifest)
    ir = load_ir_manifest(ir_manifest_path)
    ir_sha = sha256_file(ir_manifest_path)
    nfiles = len(ir.get('files') or [])

    out_root = Path(args.out_root)
    out_root.mkdir(parents=True, exist_ok=True)

    write_text(out_root / 'problem.smt2', gen_problem(ir_sha, nfiles))

    readme = f"""# STUNIR SMT2 target ({args.variant})

This directory is generated.

- `problem.smt2` is a deterministic v0 stub that binds the IR manifest digest in comments.
- The solver-backed variant (z3) captures solver stdout as a separate artifact.
"""
    write_text(out_root / 'README.md', readme)


if __name__ == '__main__':
    main()
