#!/usr/bin/env python3
"""Emit deterministic Python source artifacts from the emitted IR manifest.

v0 semantics: this is an "IR introspection" backend.
It binds the IR manifest contents into a small deterministic program.
"""

import argparse
import hashlib
import json
from pathlib import Path


def sha256_bytes(b: bytes) -> str:
    return hashlib.sha256(b).hexdigest()


def read_bytes(p: Path) -> bytes:
    return p.read_bytes()


def load_ir_manifest(path: Path) -> dict:
    obj = json.loads(path.read_text(encoding='utf-8'))
    if not isinstance(obj, dict) or obj.get('schema') not in ('stunir.ir_manifest.v2',):
        raise SystemExit(f'Unexpected IR manifest schema in {path}: {obj.get("schema")!r}')
    return obj


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding='utf-8', newline='
')


def gen_runtime_py() -> str:
    return """# Generated by STUNIR (python backend, v0)

from __future__ import annotations

import hashlib
import json
from pathlib import Path


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open('rb') as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b''):
            h.update(chunk)
    return h.hexdigest()


def find_repo_root(start: Path) -> Path:
    cur = start.resolve()
    for _ in range(0, 16):
        if (cur / 'receipts' / 'ir_manifest.json').exists() and (cur / 'asm' / 'ir').exists():
            return cur
        if cur.parent == cur:
            break
        cur = cur.parent
    raise RuntimeError('Could not locate repo root from ' + str(start))


def load_json(path: Path):
    return json.loads(path.read_text(encoding='utf-8'))
"""


def gen_program_py(variant: str) -> str:
    return f"""# Generated by STUNIR (python backend, v0)

from __future__ import annotations

import json
from pathlib import Path

from runtime import find_repo_root, load_json, sha256_file


def main() -> None:
    here = Path(__file__).resolve()
    repo = find_repo_root(here.parent)

    ir_manifest_path = repo / 'receipts' / 'ir_manifest.json'
    ir = load_json(ir_manifest_path)

    out = {{
        'schema': 'stunir.python_sample_run.v0',
        'variant': {variant!r},
        'ir_manifest_sha256': sha256_file(ir_manifest_path),
        'ir_files_count': len(ir.get('files') or []),
        'ir_files': [{{'file': f.get('file'), 'sha256': f.get('sha256'), 'bytes_len': f.get('bytes_len')}} for f in (ir.get('files') or [])],
    }}

    print(json.dumps(out, ensure_ascii=False, sort_keys=True, separators=(',', ':')))


if __name__ == '__main__':
    main()
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument('--variant', required=True, choices=['portable', 'cpython'])
    ap.add_argument('--ir-manifest', required=True)
    ap.add_argument('--out-root', required=True)
    args = ap.parse_args()

    _ = load_ir_manifest(Path(args.ir_manifest))

    out_root = Path(args.out_root)
    out_root.mkdir(parents=True, exist_ok=True)

    write_text(out_root / 'runtime.py', gen_runtime_py())
    write_text(out_root / 'program.py', gen_program_py(args.variant))

    readme = f"""# STUNIR Python target ({args.variant})

This directory is generated.

- `program.py` prints a deterministic JSON summary derived from `receipts/ir_manifest.json`.
- This is a v0 introspection backend, intended to bootstrap the pipeline and determinism checks.
"""
    write_text(out_root / 'README.md', readme)


if __name__ == '__main__':
    main()
