# STUNIR Pipeline Target Emission Test Script
# Tests full pipeline for Clojure, ClojureScript, Futhark, Lean4, and C99
# Copyright (C) 2026 STUNIR Project
# SPDX-License-Identifier: Apache-2.0

param(
    [string]$SparkDir = "C:\Users\MSTAR\AppData\Roaming\AbacusAI\Agent Workspaces\STUNIR\tools\spark",
    [string]$TestDir = "test\pipeline_targets"
)

$ErrorActionPreference = "Stop"
$PassCount = 0
$FailCount = 0

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "STUNIR Pipeline Target Emission Tests" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Change to spark directory
Set-Location $SparkDir

# Test targets with expected extensions and headers
$Targets = @(
    @{ Name = "clojure"; Extension = ".clj"; Header = ";; Generated by STUNIR" },
    @{ Name = "cljs"; Extension = ".cljs"; Header = ";; Generated by STUNIR" },
    @{ Name = "futhark"; Extension = ".fut"; Header = "-- Generated by STUNIR" },
    @{ Name = "lean4"; Extension = ".lean"; Header = "-- Generated by STUNIR" },
    @{ Name = "c99"; Extension = ".c"; Header = "// Generated by STUNIR" }
)

# Helper function to run a test
function Invoke-Test {
    param(
        [string]$Name,
        [scriptblock]$TestBlock
    )
    
    Write-Host "Testing: $Name" -NoNewline
    try {
        & $TestBlock
        Write-Host " [PASS]" -ForegroundColor Green
        $script:PassCount++
        return $true
    }
    catch {
        Write-Host " [FAIL]" -ForegroundColor Red
        Write-Host "  Error: $($_.Exception.Message)" -ForegroundColor Red
        $script:FailCount++
        return $false
    }
}

# Test each target
foreach ($Target in $Targets) {
    $TargetName = $Target.Name
    $ExpectedExt = $Target.Extension
    $ExpectedHeader = $Target.Header
    $OutputDir = Join-Path $TestDir "output_$TargetName"
    
    Invoke-Test "Pipeline emission for $TargetName" {
        # Clean output directory
        if (Test-Path $OutputDir) { 
            Remove-Item $OutputDir -Recurse -Force 
        }
        New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null
        
        # Run pipeline_driver_main
        $InputPath = Join-Path $TestDir "test_extract.json"
        $Result = & bin\pipeline_driver_main.exe -i $InputPath -o $OutputDir --target $TargetName 2>&1
        
        if ($LASTEXITCODE -ne 0) {
            throw "Pipeline failed with exit code $LASTEXITCODE : $Result"
        }
        
        # Find output file with expected extension
        $OutputFile = Get-ChildItem -Path $OutputDir -Filter "*$ExpectedExt" -ErrorAction SilentlyContinue | Select-Object -First 1
        
        if (-not $OutputFile) {
            # List what files were created for debugging
            $Files = Get-ChildItem -Path $OutputDir -ErrorAction SilentlyContinue
            $FileList = if ($Files) { $Files.Name -join ", " } else { "(none)" }
            throw "No output file with extension '$ExpectedExt' found. Files: $FileList"
        }
        
        # Verify header
        $Content = Get-Content $OutputFile.FullName -Raw
        if (-not ($Content -match [regex]::Escape($ExpectedHeader))) {
            throw "Output file missing expected header: '$ExpectedHeader'"
        }
        
        # Verify function name appears (basic content check)
        if (-not ($Content -match "compute")) {
            throw "Output file missing expected function 'compute'"
        }
        
        Write-Host " (output: $($OutputFile.Name))" -NoNewline
    }
}

# Test emit_target_main directly for each target (additional coverage)
Write-Host ""
Write-Host "--- Direct emit_target_main tests ---" -ForegroundColor Cyan

# First create a test IR file
$TestIRPath = Join-Path $TestDir "test_ir.json"
$TestIRContent = @"
{
  "schema": "stunir_ir_v1",
  "ir_version": "1.0",
  "module_name": "emit_test",
  "functions": [
    {
      "name": "calculate",
      "return_type": "int",
      "args": [],
      "steps": []
    }
  ]
}
"@
$TestIRContent | Out-File -FilePath $TestIRPath -Encoding utf8

foreach ($Target in $Targets) {
    $TargetName = $Target.Name
    $ExpectedExt = $Target.Extension
    $ExpectedHeader = $Target.Header
    $OutputFile = Join-Path $TestDir "emit_$TargetName$ExpectedExt"
    
    Invoke-Test "Direct emit for $TargetName" {
        # Remove output if exists
        if (Test-Path $OutputFile) { Remove-Item $OutputFile -Force }
        
        # Run emit_target_main
        $Result = & bin\emit_target_main.exe $TestIRPath $TargetName $OutputFile 2>&1
        
        if ($LASTEXITCODE -ne 0) {
            throw "emit_target_main failed: $Result"
        }
        
        # Verify output exists
        if (-not (Test-Path $OutputFile)) {
            throw "Output file not created: $OutputFile"
        }
        
        # Verify header
        $Content = Get-Content $OutputFile -Raw
        if (-not ($Content -match [regex]::Escape($ExpectedHeader))) {
            throw "Output missing expected header: '$ExpectedHeader'"
        }
    }
}

# Summary
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Test Summary" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Passed: $PassCount" -ForegroundColor Green
Write-Host "Failed: $FailCount" -ForegroundColor $(if ($FailCount -gt 0) { "Red" } else { "Green" })
Write-Host ""

# Cleanup
Write-Host "Cleaning up test outputs..." -ForegroundColor Yellow
foreach ($Target in $Targets) {
    $OutputDir = Join-Path $TestDir "output_$($Target.Name)"
    if (Test-Path $OutputDir) {
        Remove-Item $OutputDir -Recurse -Force
    }
    $OutputFile = Join-Path $TestDir "emit_$($Target.Name)$($Target.Extension)"
    if (Test-Path $OutputFile) {
        Remove-Item $OutputFile -Force
    }
}
if (Test-Path $TestIRPath) {
    Remove-Item $TestIRPath -Force
}

if ($FailCount -gt 0) {
    exit 1
}
exit 0