use crate::ir_v1::IrV1;
use crate::errors::StunirError;
use anyhow::Result;
use std::fs;
use std::path::Path;

pub fn emit(ir: &IrV1, out_file: &str) -> Result<()> {
    let mut code = String::new();

    // Header
    code.push_str("# Generated by STUNIR Native Core (Rust)\n");
    code.push_str("# Target: Python\n\n");

    // Functions
    for func in &ir.functions {
        code.push_str(&format!("def {}():\n", func.name));

        if func.body.is_empty() {
            code.push_str("    pass\n");
        }

        for instr in &func.body {
            match instr.op.as_str() {
                "print" => {
                    // Simple print wrapper - ESCAPED QUOTES
                    if let Some(arg) = instr.args.get(0) {
                        code.push_str(&format!("    print(\"{}\")\n", arg));
                    }
                },
                "comment" => {
                    // Python comment
                    if let Some(arg) = instr.args.get(0) {
                        code.push_str(&format!("    # {}\n", arg));
                    }
                },
                "raw" => {
                    // Emit raw code lines (indenting them)
                    if let Some(arg) = instr.args.get(0) {
                        for line in arg.lines() {
                            code.push_str(&format!("    {}\n", line));
                        }
                    }
                },
                "call" => {
                    // Function call
                    if let Some(arg) = instr.args.get(0) {
                        code.push_str(&format!("    {}()\n", arg));
                    }
                },
                _ => {
                    code.push_str(&format!("    # Unknown Op: {}\n", instr.op));
                }
            }
        }
        code.push_str("\n");
    }

    // Entry Point
    code.push_str("if __name__ == \"__main__\":\n");
    code.push_str("    main()\n");

    // Write to file
    if let Some(parent) = Path::new(out_file).parent() {
        fs::create_dir_all(parent).map_err(|e| StunirError::Io(e.to_string()))?;
    }

    fs::write(out_file, code).map_err(|e| StunirError::Io(e.to_string()))?;
    println!("Emitted Python code to {}", out_file);

    Ok(())
}
