--  STUNIR Systems Emitter - Ada SPARK Specification
--  Systems programming emitter (C, C++, Rust, Zig, Ada)
--  DO-178C Level A compliant
--  Generated by: STUNIR Emitter Generator v1.0
--  Timestamp: 2026-01-31T02:44:18.974822Z

pragma SPARK_Mode (On);

with Emitter_Types; use Emitter_Types;

package Systems_Emitter is

   --  Systems target configuration
   type Systems_Config is record
      Language : String;
      Standard : String;
      Use_Safe_Apis : Boolean;
   end record;

   --  Default configuration
   Default_Config : constant Systems_Config := (
      Language => c,
      Standard => c11,
      Use_Safe_Apis => True
   );

   --  Main emission procedure with SPARK contracts
   procedure Emit_Module (
      Name      : in Identifier_String;
      Content   : out Content_String;
      Config    : in Systems_Config;
      Status    : out Emitter_Status)
      with Pre => Identifier_Strings.Length (Name) > 0,
           Post => (Status = Success) = (Content_Strings.Length (Content) > 0);

   --  Emit function code
   procedure Emit_Function (
      Func_Name : in Identifier_String;
      Params    : in String;
      Body_Code : in String;
      Content   : out Content_String;
      Status    : out Emitter_Status)
      with Pre => Identifier_Strings.Length (Func_Name) > 0;

   --  Type mapping from IR to Systems
   function Map_Type_To_SYSTEMS (IR_Type : IR_Data_Type) return Type_Name_String;

end Systems_Emitter;
