"""Multi-Target Generation Tests

Tests generating multiple targets from the same IR.
"""

import json
from pathlib import Path
from typing import Dict, Any, List

import pytest

from .utils import (
    compute_sha256,
    canonical_json,
    create_test_ir,
    save_json_file,
)


def emit_python_target(ir: Dict[str, Any]) -> str:
    """Emit Python code from IR."""
    lines = [
        "# Generated by STUNIR",
        f"# Module: {ir.get('module_name', 'unknown')}",
        "",
    ]

    for func in ir.get("functions", []):
        lines.append(f"def {func['name']}():")
        if func.get("body"):
            for instr in func["body"]:
                op = instr.get("op", "nop")
                args = instr.get("args", [])
                if op == "print":
                    lines.append(f"    print({repr(args[0] if args else '')})")
                elif op == "raw":
                    for arg in args:
                        lines.append(f"    # {arg[:50]}..." if len(arg) > 50 else f"    # {arg}")
                else:
                    lines.append(f"    pass  # {op}")
        else:
            lines.append("    pass")
        lines.append("")

    return "\n".join(lines)


def emit_bash_target(ir: Dict[str, Any]) -> str:
    """Emit Bash script from IR."""
    lines = [
        "#!/bin/bash",
        f"# Generated by STUNIR",
        f"# Module: {ir.get('module_name', 'unknown')}",
        "",
    ]

    for func in ir.get("functions", []):
        lines.append(f"{func['name']}() {{")
        if func.get("body"):
            for instr in func["body"]:
                op = instr.get("op", "nop")
                args = instr.get("args", [])
                if op == "print":
                    lines.append(f'    echo "{args[0] if args else ""}"')
                elif op == "raw":
                    lines.append(f"    # Raw: {args[0][:30] if args else 'empty'}...")
                else:
                    lines.append(f"    # {op}")
        else:
            lines.append("    :")
        lines.append("}")
        lines.append("")

    return "\n".join(lines)


def emit_javascript_target(ir: Dict[str, Any]) -> str:
    """Emit JavaScript code from IR."""
    lines = [
        "// Generated by STUNIR",
        f"// Module: {ir.get('module_name', 'unknown')}",
        "",
    ]

    for func in ir.get("functions", []):
        lines.append(f"function {func['name']}() {{")
        if func.get("body"):
            for instr in func["body"]:
                op = instr.get("op", "nop")
                args = instr.get("args", [])
                if op == "print":
                    lines.append(f"    console.log({json.dumps(args[0] if args else '')});")
                elif op == "raw":
                    lines.append(f"    // {args[0][:50] if args else 'empty'}...")
                else:
                    lines.append(f"    // {op}")
        else:
            lines.append("    // nop")
        lines.append("}")
        lines.append("")

    return "\n".join(lines)


class TestMultiTargetGeneration:
    """Test generating multiple targets from same IR."""

    def test_generate_all_targets(self, temp_dir: Path):
        """Test generating Python, Bash, and JavaScript from same IR."""
        ir = create_test_ir("multi-target", functions=2)

        # Generate all targets
        python_code = emit_python_target(ir)
        bash_code = emit_bash_target(ir)
        js_code = emit_javascript_target(ir)

        # Save targets
        targets_dir = temp_dir / "targets"
        targets_dir.mkdir()

        (targets_dir / "output.py").write_text(python_code)
        (targets_dir / "output.sh").write_text(bash_code)
        (targets_dir / "output.js").write_text(js_code)

        # Verify all targets were generated
        assert (targets_dir / "output.py").exists()
        assert (targets_dir / "output.sh").exists()
        assert (targets_dir / "output.js").exists()

        # Verify each target has content
        assert len(python_code) > 50
        assert len(bash_code) > 50
        assert len(js_code) > 50

    def test_targets_preserve_function_names(self):
        """Test all targets preserve function names from IR."""
        ir = {
            "kind": "ir",
            "generator": "test",
            "ir_version": "v1",
            "module_name": "test",
            "functions": [
                {"name": "initialize", "body": [{"op": "nop", "args": []}]},
                {"name": "process", "body": [{"op": "nop", "args": []}]},
                {"name": "cleanup", "body": [{"op": "nop", "args": []}]},
            ],
            "modules": [],
            "metadata": {"original_spec_kind": "spec", "source_modules": []}
        }

        python_code = emit_python_target(ir)
        bash_code = emit_bash_target(ir)
        js_code = emit_javascript_target(ir)

        # Check function names in each target
        for name in ["initialize", "process", "cleanup"]:
            assert name in python_code, f"Python missing function: {name}"
            assert name in bash_code, f"Bash missing function: {name}"
            assert name in js_code, f"JavaScript missing function: {name}"

    def test_target_generation_determinism(self):
        """Test target generation is deterministic."""
        ir = create_test_ir("determinism", functions=3)

        # Generate multiple times
        results = {
            "python": [],
            "bash": [],
            "js": []
        }

        for _ in range(3):
            results["python"].append(emit_python_target(ir))
            results["bash"].append(emit_bash_target(ir))
            results["js"].append(emit_javascript_target(ir))

        # All outputs should be identical
        for lang, outputs in results.items():
            first = outputs[0]
            for i, output in enumerate(outputs[1:], 2):
                assert output == first, \
                    f"{lang} output differs at iteration {i}"

    def test_target_hashes_consistent(self, temp_dir: Path):
        """Test target hashes are consistent across generations."""
        ir = create_test_ir("hash-test", functions=2)

        # Generate and hash targets
        hashes = {}
        for i in range(3):
            python_code = emit_python_target(ir)
            bash_code = emit_bash_target(ir)
            js_code = emit_javascript_target(ir)

            round_hashes = {
                "python": compute_sha256(python_code),
                "bash": compute_sha256(bash_code),
                "js": compute_sha256(js_code)
            }

            if i == 0:
                hashes = round_hashes
            else:
                for lang in ["python", "bash", "js"]:
                    assert round_hashes[lang] == hashes[lang], \
                        f"{lang} hash changed at iteration {i+1}"


class TestTargetConsistency:
    """Test consistency between targets."""

    def test_all_targets_have_same_functions(self):
        """Test all targets define the same functions."""
        ir = create_test_ir("consistency", functions=4)

        python_code = emit_python_target(ir)
        bash_code = emit_bash_target(ir)
        js_code = emit_javascript_target(ir)

        # Count function definitions
        python_funcs = python_code.count("def ")
        bash_funcs = bash_code.count("() {")
        js_funcs = js_code.count("function ")

        expected = len(ir["functions"])
        assert python_funcs == expected, \
            f"Python has {python_funcs} functions, expected {expected}"
        assert bash_funcs == expected, \
            f"Bash has {bash_funcs} functions, expected {expected}"
        assert js_funcs == expected, \
            f"JavaScript has {js_funcs} functions, expected {expected}"

    def test_ir_hash_stable_with_different_targets(self, temp_dir: Path):
        """Test IR hash remains stable regardless of target generation."""
        ir = create_test_ir("stable-ir", functions=2)
        ir_json = canonical_json(ir)
        original_hash = compute_sha256(ir_json)

        # Generate all targets
        emit_python_target(ir)
        emit_bash_target(ir)
        emit_javascript_target(ir)

        # IR should not be modified
        post_hash = compute_sha256(canonical_json(ir))
        assert post_hash == original_hash, "IR was modified during target generation"

    def test_manifest_tracks_all_targets(self, temp_dir: Path):
        """Test manifest correctly tracks all generated targets."""
        ir = create_test_ir("manifest-test", functions=1)

        # Generate targets
        targets = {
            "output.py": emit_python_target(ir),
            "output.sh": emit_bash_target(ir),
            "output.js": emit_javascript_target(ir)
        }

        # Save targets
        targets_dir = temp_dir / "targets"
        targets_dir.mkdir()
        for name, content in targets.items():
            (targets_dir / name).write_text(content)

        # Create manifest
        manifest_entries = []
        for name, content in sorted(targets.items()):
            manifest_entries.append({
                "name": name,
                "hash": compute_sha256(content),
                "size": len(content),
                "type": name.split(".")[-1]
            })

        manifest = {
            "schema": "stunir.manifest.targets.v1",
            "entries": manifest_entries,
            "count": len(manifest_entries)
        }

        # Verify manifest
        assert manifest["count"] == 3
        types = {e["type"] for e in manifest["entries"]}
        assert types == {"py", "sh", "js"}
