/* STUNIR Generated Code
 * Generated by: stunir_ir_to_code_spark v0.7.1
 * Module: mixed_nesting
 */

#include <stdint.h>
#include <stdbool.h>

void test_mixed(int32_t x) {
  for (int i = 0; i < x; i++) {
    if (i % 2 == 0) {
      while (i < 10) {
  int32_t i = i + 1;
      }
  process(i);
    } else {
  process(i);
    }
  }
  return;
}

