--  STUNIR Planning Emitter - Ada SPARK Specification
--  AI planning language emitter (PDDL, STRIPS, HTN)
--  DO-178C Level A compliant
--  Generated by: STUNIR Emitter Generator v1.0
--  Timestamp: 2026-01-31T02:44:18.781168Z

pragma SPARK_Mode (On);

with Emitter_Types; use Emitter_Types;

package Planning_Emitter is

   --  Planning target configuration
   type Planning_Config is record
      Pddl_Version : String;
      Use_Types : Boolean;
      Use_Durative : Boolean;
   end record;

   --  Default configuration
   Default_Config : constant Planning_Config := (
      Pddl_Version => 2.1,
      Use_Types => True,
      Use_Durative => False
   );

   --  Main emission procedure with SPARK contracts
   procedure Emit_Module (
      Name      : in Identifier_String;
      Content   : out Content_String;
      Config    : in Planning_Config;
      Status    : out Emitter_Status)
      with Pre => Identifier_Strings.Length (Name) > 0,
           Post => (Status = Success) = (Content_Strings.Length (Content) > 0);

   --  Emit function code
   procedure Emit_Function (
      Func_Name : in Identifier_String;
      Params    : in String;
      Body_Code : in String;
      Content   : out Content_String;
      Status    : out Emitter_Status)
      with Pre => Identifier_Strings.Length (Func_Name) > 0;

   --  Type mapping from IR to Planning
   function Map_Type_To_PLANNING (IR_Type : IR_Data_Type) return Type_Name_String;

end Planning_Emitter;
