/* STUNIR Generated Code
 * Generated by: stunir_ir_to_code_spark v0.7.0
 * Module: nested_4_levels
 */

#include <stdint.h>
#include <stdbool.h>

int32_t test_nested_4(int32_t x) {
  if (x > 0) {
    if (x > 10) {
      if (x > 20) {
        if (x > 30) {
  return 300;
        } else {
  return 200;
        }
      }
  return 100;
    }
  return 10;
  }
  return 0;
}

