/* STUNIR Generated Code
 * Generated by: stunir_ir_to_code_spark v0.7.0
 * Module: nested_5_levels
 */

#include <stdint.h>
#include <stdbool.h>

int32_t test_nested_5(int32_t x) {
  if (x > 0) {
    if (x > 10) {
      if (x > 20) {
        if (x > 30) {
          if (x > 40) {
  return 400;
          } else {
  return 300;
          }
        }
  return 200;
      }
  return 100;
    }
  return 10;
  }
  return 0;
}

