--  STUNIR Business Emitter - Ada SPARK Specification
--  Business application language emitter (COBOL, ABAP, RPG)
--  DO-178C Level A compliant
--  Generated by: STUNIR Emitter Generator v1.0
--  Timestamp: 2026-01-31T02:44:17.573674Z

pragma SPARK_Mode (On);

with Emitter_Types; use Emitter_Types;

package Business_Emitter is

   --  Business target configuration
   type Business_Config is record
      Language : String;
      Cobol_Standard : String;
      Use_Copybooks : Boolean;
   end record;

   --  Default configuration
   Default_Config : constant Business_Config := (
      Language => cobol,
      Cobol_Standard => 85,
      Use_Copybooks => True
   );

   --  Main emission procedure with SPARK contracts
   procedure Emit_Module (
      Name      : in Identifier_String;
      Content   : out Content_String;
      Config    : in Business_Config;
      Status    : out Emitter_Status)
      with Pre => Identifier_Strings.Length (Name) > 0,
           Post => (Status = Success) = (Content_Strings.Length (Content) > 0);

   --  Emit function code
   procedure Emit_Function (
      Func_Name : in Identifier_String;
      Params    : in String;
      Body_Code : in String;
      Content   : out Content_String;
      Status    : out Emitter_Status)
      with Pre => Identifier_Strings.Length (Func_Name) > 0;

   --  Type mapping from IR to Business
   function Map_Type_To_BUSINESS (IR_Type : IR_Data_Type) return Type_Name_String;

end Business_Emitter;
