#!/usr/bin/env python3
# STUNIR: minimal deterministic Python codegen (portable)
from __future__ import annotations

import argparse
from pathlib import Path


def _w(p: Path, s: str) -> None:
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(s, encoding="utf-8", newline="\n")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--variant", required=True)
    ap.add_argument("--ir-manifest", required=True)
    ap.add_argument("--out-root", required=True)
    args = ap.parse_args()

    out_root = Path(args.out_root)
    out_root.mkdir(parents=True, exist_ok=True)

    program_py = "\n".join([
        "# Generated by STUNIR (python backend, minimal)",
        "from __future__ import annotations",
        "import json",
        "from pathlib import Path",
        "",
        "def _find_receipts_dir() -> Path:",
        "    p = Path(__file__).resolve()",
        "    # .../asm/python/<variant>/program.py",
        "    asm_dir = p.parents[2]  # .../asm",
        "    out_dir = asm_dir.parent  # repo root or .../samples/out/<sample>",
        "    return out_dir / 'receipts'",
        "",
        "def main() -> int:",
        "    receipts = _find_receipts_dir()",
        "    ir_manifest = receipts / 'ir_manifest.json'",
        "    if not ir_manifest.exists():",
        "        raise SystemExit(f'ir_manifest not found: {ir_manifest}')",
        "    obj = json.loads(ir_manifest.read_text(encoding='utf-8'))",
        "    files = []",
        "    if isinstance(obj, dict) and isinstance(obj.get('files'), list):",
        "        for it in obj['files']:",
        "            if isinstance(it, dict) and 'file' in it:",
        "                files.append(str(it['file']))",
        "    epoch = None",
        "    if isinstance(obj, dict):",
        "        epoch = (obj.get('epoch') or {}).get('selected_epoch')",
        "    out = {'backend': 'python', 'epoch': epoch, 'ir_files': files}",
        "    print(json.dumps(out, sort_keys=True, separators=(',',':'), ensure_ascii=False))",
        "    return 0",
        "",
        "if __name__ == '__main__':",
        "    raise SystemExit(main())",
    ]) + "\n"

    _w(out_root / "program.py", program_py)
    _w(out_root / "runtime.py", "# runtime placeholder for minimal backend\n")
    _w(out_root / "README.md", "Python output (minimal backend).\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
