// Generated by STUNIR
// Module: control_flow_test
int simple_return(int x) {
    return x;
}

int simple_assign(int a, int b) {
    result = a + b;
    return result;
}

int if_else_test(int x) {
    if (x > 0) {
        return x;
    } else {
        return -x;
    }
}

int nested_if_test(int a, int b) {
    if (a > b) {
        max = a;
    } else {
        max = b;
    }
    return max;
}

int while_loop_test(int n) {
    sum = 0;
    i = 1;
    while (i <= n) {
        sum = sum + i;
        i = i + 1;
    }
    return sum;
}

int for_loop_test(int n) {
    factorial = 1;
    for (i = 1; i <= n; i++) {
        factorial = factorial * i;
    }
    return factorial;
}

int mixed_control_flow(int[] arr, int len) {
    sum = 0;
    i = 0;
    while (i < len) {
        sum = sum + arr[i];
        i = i + 1;
    }
    return sum;
}

int call_test(int x) {
    result = simple_return(x);
    return result;
}

// End of module

