-- Generated by STUNIR
-- Module: test_module
let add (a: int) (b: int) : int =
  a + b

let factorial (n: int) : int =
  let result = 1
  let i = 1
  -- for i = 1; i <= n; i++
  --   let result = result * i
  result

let abs_value (x: int) : int =
  if x < 0 then -x else x

let count_down (n: int) : int =
  let count = 0
  -- while n > 0 (use loop expression)
  --   let count = count + 1
  --   let n = n - 1
  count

let compute (x: int) (y: int) : int =
  let result = 0
  result

-- End of module

