// Generated by STUNIR
// Module: test_module
int add(int a, int b) {
    return a + b;
}

int factorial(int n) {
    result = 1;
    i = 1;
    for (i = 1; i <= n; i++) {
        result = result * i;
    }
    return result;
}

int abs_value(int x) {
    if (x < 0) {
        return -x;
    } else {
        return x;
    }
}

int count_down(int n) {
    count = 0;
    while (n > 0) {
        count = count + 1;
        n = n - 1;
    }
    return count;
}

int compute(int x, int y) {
    result = 0;
    return result;
}

// End of module

