;; Generated by STUNIR
;; Module: test_module
(defn add [a b]
  a + b
)

(defn factorial [n]
  (set! result 1)
  (set! i 1)
  ;; for loop: i = 1; i <= n; i++
  ;;   result = result * i
  result
)

(defn abs_value [x]
  (if x < 0
    (do
      -x
    )
    (do
      x
    )
  )
)

(defn count_down [n]
  (set! count 0)
  (while n > 0 (do
    (set! count count + 1)
    (set! n n - 1)
  ))
  count
)

(defn compute [x y]
  (set! result 0)
  result
)

;; End of module

