;; Generated by STUNIR
;; Module: control_flow_test
(defun simple_return (x)
  x
)

(defun simple_assign (a b)
  (setf result a + b)
  result
)

(defun if_else_test (x)
  (if x > 0
    (progn
      x
    )
    (progn
      -x
    )
  )
)

(defun nested_if_test (a b)
  (if a > b
    (progn
      (setf max a)
    )
    (progn
      (setf max b)
    )
  )
  max
)

(defun while_loop_test (n)
  (setf sum 0)
  (setf i 1)
  (loop while i <= n do
    (setf sum sum + i)
    (setf i i + 1)
  )
  sum
)

(defun for_loop_test (n)
  (setf factorial 1)
  ;; for loop: use loop macro
  (loop for i from 1 to n do
    (setf factorial factorial * i)
  )
  factorial
)

(defun mixed_control_flow (arr len)
  (setf sum 0)
  (setf i 0)
  (loop while i < len do
    (setf sum sum + arr[i])
    (setf i i + 1)
  )
  sum
)

(defun call_test (x)
  (setf result (simple_return x))
  result
)

;; End of module

