-- Generated by STUNIR
-- Module: test_module
def add (a : int) (b : int) : int :=
  a + b

def factorial (n : int) : int :=
  let result := 1
  let i := 1
  -- for i = 1; i <= n; i++
  --   let result := result * i
  result

def abs_value (x : int) : int :=
  if x < 0 then -x else x

def count_down (n : int) : int :=
  let count := 0
  -- while n > 0 (use forM or recursion)
  --   let count := count + 1
  --   let n := n - 1
  count

def compute (x : int) (y : int) : int :=
  let result := 0
  result

-- End of module

