;; Generated by STUNIR
;; Module: control_flow_test
(defn simple_return [x]
  x
)

(defn simple_assign [a b]
  (set! result a + b)
  result
)

(defn if_else_test [x]
  (if x > 0
    (do
      x
    )
    (do
      -x
    )
  )
)

(defn nested_if_test [a b]
  (if a > b
    (do
      (set! max a)
    )
    (do
      (set! max b)
    )
  )
  max
)

(defn while_loop_test [n]
  (set! sum 0)
  (set! i 1)
  (while i <= n (do
    (set! sum sum + i)
    (set! i i + 1)
  ))
  sum
)

(defn for_loop_test [n]
  (set! factorial 1)
  ;; for loop: i = 1; i <= n; i++
  ;;   factorial = factorial * i
  factorial
)

(defn mixed_control_flow [arr len]
  (set! sum 0)
  (set! i 0)
  (while i < len (do
    nil
    (set! i i + 1)
  ))
  sum
)

(defn call_test [x]
  (simple_return x)
  result
)

;; End of module

