--  STUNIR Lexer Emitter - Ada SPARK Implementation
--  Lexer/tokenizer generator for multiple languages
--  DO-178C Level A compliant
--  Generated by: STUNIR Emitter Generator v1.0
--  Timestamp: 2026-01-31T02:44:18.376788Z

pragma SPARK_Mode (On);

with Ada.Text_IO;

package body Lexer_Emitter is

   New_Line : constant Character := ASCII.LF;

   --  Helper to append string to content buffer
   procedure Append_To_Content (
      Content : in out Content_String;
      Text    : in String;
      Status  : out Emitter_Status)
   is
      Current_Len : constant Natural := Content_Strings.Length (Content);
   begin
      if Current_Len + Text'Length > Max_Content_Length then
         Status := Error_Buffer_Overflow;
      else
         Content_Strings.Append (Content, Text);
         Status := Success;
      end if;
   end Append_To_Content;

   --  Map IR type to Lexer type
   function Map_Type_To_LEXER (IR_Type : IR_Data_Type) return Type_Name_String
   is
   begin
      case IR_Type is
         when Type_I32 =>
            return Type_Name_Strings.To_Bounded_String ("i32");
         when Type_I64 =>
            return Type_Name_Strings.To_Bounded_String ("i64");
         when Type_F32 =>
            return Type_Name_Strings.To_Bounded_String ("f32");
         when Type_F64 =>
            return Type_Name_Strings.To_Bounded_String ("f64");
         when Type_Bool =>
            return Type_Name_Strings.To_Bounded_String ("bool");
         when others =>
            return Type_Name_Strings.To_Bounded_String ("i32");
      end case;
   end Map_Type_To_LEXER;

   --  Emit function code
   procedure Emit_Function (
      Func_Name : in Identifier_String;
      Params    : in String;
      Body_Code : in String;
      Content   : out Content_String;
      Status    : out Emitter_Status)
   is
   begin
      Content := Content_Strings.Null_Bounded_String;
      Status := Success;

      --  Function header
      Append_To_Content (Content, "function " & 
         Identifier_Strings.To_String (Func_Name) & "(" & 
         Params & ") {" & New_Line, Status);
      
      if Status /= Success then
         return;
      end if;

      --  Function body
      Append_To_Content (Content, Body_Code & New_Line, Status);
      
      if Status /= Success then
         return;
      end if;

      --  Function footer
      Append_To_Content (Content, "}" & New_Line, Status);
   end Emit_Function;

   --  Emit complete module
   procedure Emit_Module (
      Name      : in Identifier_String;
      Content   : out Content_String;
      Config    : in Lexer_Config;
      Status    : out Emitter_Status)
   is
      pragma Unreferenced (Config);
   begin
      Content := Content_Strings.Null_Bounded_String;
      Status := Success;

      --  Header comments
      Append_To_Content (Content, "/* STUNIR Generated Lexer Code */" & New_Line, Status);
      Append_To_Content (Content, "/* Module: " & Identifier_Strings.To_String (Name) & " */" & New_Line, Status);
      Append_To_Content (Content, "/* Generator: SPARK Pipeline */" & New_Line, Status);
      Append_To_Content (Content, "/* DO-178C Level A compliant */" & New_Line, Status);
      Append_To_Content (Content, New_Line, Status);

      if Status /= Success then
         return;
      end if;

      --  Module body
      Append_To_Content (Content, "// Lexer implementation goes here" & New_Line, Status);
   end Emit_Module;

end Lexer_Emitter;
