/* STUNIR Embedded Configuration: module */
/* Generated by STUNIR Embedded Emitter */

#ifndef CONFIG_H
#define CONFIG_H

/* Architecture */
#define STUNIR_ARCH_ARM 1
#define STUNIR_WORD_SIZE 32
#define STUNIR_ENDIAN_LITTLE 1

/* Memory configuration */
#define STUNIR_STACK_SIZE 1024
#define STUNIR_HEAP_SIZE 0

/* Feature flags */
#define STUNIR_NO_MALLOC 1
#define STUNIR_NO_STDIO 1
#define STUNIR_NO_FLOAT 0

/* Epoch */
#define STUNIR_BUILD_EPOCH 1769856341

#endif /* CONFIG_H */
