--  STUNIR Functional Emitter - Ada SPARK Specification
--  Functional language emitter
--  DO-178C Level A compliant
--  Generated by: STUNIR Emitter Generator v1.0
--  Timestamp: 2026-02-04T12:19:06.211328Z

pragma SPARK_Mode (On);

with Emitter_Types; use Emitter_Types;

package Functional_Emitter is

   --  Functional target configuration
   type Functional_Config is record
      Use_Immutable_Data : Boolean;
   end record;

   --  Default configuration
   Default_Config : constant Functional_Config := (
      Use_Immutable_Data => True
   );

   --  Main emission procedure with SPARK contracts
   procedure Emit_Module (
      Name      : in Identifier_String;
      Content   : out Content_String;
      Config    : in Functional_Config;
      Status    : out Emitter_Status)
      with Pre => Identifier_Strings.Length (Name) > 0,
           Post => (Status = Success) = (Content_Strings.Length (Content) > 0);

   --  Emit function code
   procedure Emit_Function (
      Func_Name : in Identifier_String;
      Params    : in String;
      Body_Code : in String;
      Content   : out Content_String;
      Status    : out Emitter_Status)
      with Pre => Identifier_Strings.Length (Func_Name) > 0;

   --  Type mapping from IR to Functional
   function Map_Type_To_FUNCTIONAL (IR_Type : IR_Data_Type) return Type_Name_String;

end Functional_Emitter;
