/* STUNIR Generated Code
 * Generated by: stunir_ir_to_code_spark v0.7.1
 * Module: nested_4_levels
 */

#include <stdint.h>
#include <stdbool.h>

int32_t test_nested_4(int32_t x) {
  if (x > 0) {
    if (x > 10) {
      if (x > 20) {
        while (x > 0) {
  int32_t x = x - 1;
        }
  return 0;
      }
    }
  }
  return x;

}

