/* STUNIR Generated Code
 * Generated by: stunir_ir_to_code_spark v0.7.1
 * Module: break_nested_test
 */

#include <stdint.h>
#include <stdbool.h>

int32_t find_pair_sum(int32_t target) {
  uint8_t found = 0;
  for (i = 0; i < 10; i = i + 1) {
    for (j = 0; j < 10; j = j + 1) {
      if (i + j == target) {
  uint8_t found = 1;
        break;
      }
    }
    if (found == 1) {
      break;
    }
  }
  return found;

}

