/* STUNIR Generated Code
 * Generated by: stunir_ir_to_code_spark v0.7.1
 * Module: continue_for_test
 */

#include <stdint.h>
#include <stdbool.h>

int32_t sum_odd_numbers(int32_t max) {
  uint8_t sum = 0;
  for (i = 0; i < max; i = i + 1) {
    if (i % 2 == 0) {
      continue;
    }
  int32_t sum = sum + i;
  }
  return sum;

}

