/**
 * STUNIR Type Definitions
 * These interfaces describe the core data structures used in the STUNIR ecosystem.
 * Use these as the "Ground Truth" for JSON schemas and object shapes.
 */

// --- Manifests ---

/**
 * STUNIR Manifest V1
 * A line-based text format. Each line is: "<SHA256>  <PATH>"
 * Sorted by byte comparison.
 */
export type ManifestV1 = string; // Raw text content

/**
 * The parsed representation of a Manifest line
 */
export interface ManifestEntry {
  sha256: string;
  path: string; // Relative, forward slashes, no leading ./
}

// --- Receipts ---

/**
 * The Shell-Native Receipt (KV-Text)
 * Used in Profile 3 (No Python).
 */
export interface ReceiptKV {
  STUNIR_VERSION: string;
  STUNIR_PROFILE: "SHELL_NATIVE" | "PYTHON_FULL" | "COMPILED";
  BUILD_TIMESTAMP: string; // ISO8601 from Epoch
  GIT_COMMIT?: string;
  MANIFEST_HASH: string;
  [key: string]: string; // Extensible fields
}

/**
 * The Canonical Receipt (JSON)
 * Used in Profile 1 & 2.
 */
export interface ReceiptJSON {
  meta: {
    id: string;
    timestamp: string;
    epoch: number;
  };
  inputs: {
    spec_digest: string;
    toolchain_digest: string;
  };
  outputs: {
    artifacts: Record<string, string>; // Path -> Hash
  };
  tools: {
    name: string;
    version: string;
    digest: string;
  }[];
}

// --- Environment ---

/**
 * Host Environment Allowlist
 * Defines which env vars are permitted to leak into the build.
 */
export interface HostEnvAllowlist {
  comment: string;
  policy: "STRICT" | "PERMISSIVE";
  allowed_vars: string[];
  blocked_vars: string[]; // Explicitly forbidden (e.g. PATH)
  required_vars?: string[];
}

// --- Toolchain ---

/**
 * Local Toolchain Lockfile
 * Generated by discovery, consumed by build.
 */
export interface LocalToolchainLock {
  tools: {
    [logicalName: string]: { // e.g. "PYTHON", "CC", "GIT"
      path: string; // Absolute path on host
      sha256: string; // Content hash of the executable
      version_output: string; // Output of --version
    };
  };
  host_info: {
    platform: string;
    arch: string;
  };
}
