/* STUNIR Generated Code
 * Generated by: stunir_ir_to_code_spark v0.7.1
 * Module: nested_2_levels
 */

#include <stdint.h>
#include <stdbool.h>

int32_t test_nested_2(int32_t x) {
  if (x > 0) {
  }
  return 0;
}

