# STUNIR IR Tools Test Script
# Tests all decomposed IR tools
# Copyright (C) 2026 STUNIR Project
# SPDX-License-Identifier: Apache-2.0

param(
    [string]$SparkDir = "C:\Users\MSTAR\AppData\Roaming\AbacusAI\Agent Workspaces\STUNIR\tools\spark",
    [string]$TestDir = "test\ir_tools"
)

$ErrorActionPreference = "Stop"
$PassCount = 0
$FailCount = 0

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "STUNIR Micro-Tools Test Suite" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Helper function to run a test
function Invoke-Test {
    param(
        [string]$Name,
        [scriptblock]$TestBlock
    )
    
    Write-Host "Testing: $Name" -NoNewline
    try {
        & $TestBlock
        Write-Host " [PASS]" -ForegroundColor Green
        $script:PassCount++
        return $true
    }
    catch {
        Write-Host " [FAIL]" -ForegroundColor Red
        Write-Host "  Error: $($_.Exception.Message)" -ForegroundColor Red
        $script:FailCount++
        return $false
    }
}

# Change to spark directory
Set-Location $SparkDir

# Test 1: Extract Parse
Invoke-Test "extract_parse - Parse extraction JSON" {
    $extractPath = Join-Path $TestDir "test_extract.json"
    $outputPath = Join-Path $TestDir "output_extract.json"
    
    # This would call extract_parse if it had a main - for now we test via assemble_spec
    if (-not (Test-Path $extractPath)) {
        throw "Test file not found: $extractPath"
    }
    $content = Get-Content $extractPath -Raw | ConvertFrom-Json
    if ($content.module_name -ne "test_module") {
        throw "Unexpected module_name: $($content.module_name)"
    }
}

# Test 2: Assemble Spec
Invoke-Test "assemble_spec_main - Assemble spec from extraction" {
    $extractPath = Join-Path $TestDir "test_extract.json"
    $specPath = Join-Path $TestDir "output_spec.json"
    
    # Remove output if exists
    if (Test-Path $specPath) { Remove-Item $specPath -Force }
    
    # Run assemble_spec_main
    $result = & bin\assemble_spec_main.exe $extractPath $specPath 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "assemble_spec_main failed: $result"
    }
    
    # Verify output
    if (-not (Test-Path $specPath)) {
        throw "Output file not created: $specPath"
    }
    
    $spec = Get-Content $specPath -Raw | ConvertFrom-Json
    if ($spec.module_name -ne "test_module") {
        throw "Unexpected module_name in spec: $($spec.module_name)"
    }
}

# Test 3: Spec Parse
Invoke-Test "spec_parse - Parse spec JSON" {
    $specPath = Join-Path $TestDir "test_spec.json"
    
    if (-not (Test-Path $specPath)) {
        throw "Test file not found: $specPath"
    }
    
    $spec = Get-Content $specPath -Raw | ConvertFrom-Json
    if ($spec.schema -ne "stunir_spec_v1") {
        throw "Unexpected schema: $($spec.schema)"
    }
}

# Test 4: Spec to IR
Invoke-Test "spec_to_ir_main - Convert spec to IR" {
    $specPath = Join-Path $TestDir "test_spec.json"
    $irPath = Join-Path $TestDir "output_ir.json"
    
    # Remove output if exists
    if (Test-Path $irPath) { Remove-Item $irPath -Force }
    
    # Run spec_to_ir_main
    $result = & bin\spec_to_ir_main.exe $specPath $irPath 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "spec_to_ir_main failed: $result"
    }
    
    # Verify output
    if (-not (Test-Path $irPath)) {
        throw "Output file not created: $irPath"
    }
    
    $ir = Get-Content $irPath -Raw | ConvertFrom-Json
    if ($ir.module_name -ne "test_module") {
        throw "Unexpected module_name in IR: $($ir.module_name)"
    }
}

# Test 5: IR Parse
Invoke-Test "ir_parse - Parse IR JSON" {
    $irPath = Join-Path $TestDir "test_ir.json"
    
    if (-not (Test-Path $irPath)) {
        throw "Test file not found: $irPath"
    }
    
    $ir = Get-Content $irPath -Raw | ConvertFrom-Json
    if ($ir.schema -ne "stunir_ir_v1") {
        throw "Unexpected schema: $($ir.schema)"
    }
}

# Test 6: Emit Target (Python)
Invoke-Test "emit_target_main - Emit Python code" {
    $irPath = Join-Path $TestDir "test_ir.json"
    $outputPath = Join-Path $TestDir "output.py"
    
    # Remove output if exists
    if (Test-Path $outputPath) { Remove-Item $outputPath -Force }
    
    # Run emit_target_main
    $result = & bin\emit_target_main.exe $irPath python $outputPath 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "emit_target_main failed: $result"
    }
    
    # Verify output
    if (-not (Test-Path $outputPath)) {
        throw "Output file not created: $outputPath"
    }
    
    $code = Get-Content $outputPath -Raw
    if (-not ($code -match "# Generated by STUNIR")) {
        throw "Output missing expected header"
    }
    if (-not ($code -match "def add")) {
        throw "Output missing expected function"
    }
}

# Test 7: Emit Target (C++)
Invoke-Test "emit_target_main - Emit C++ code" {
    $irPath = Join-Path $TestDir "test_ir.json"
    $outputPath = Join-Path $TestDir "output.cpp"
    
    # Remove output if exists
    if (Test-Path $outputPath) { Remove-Item $outputPath -Force }
    
    # Run emit_target_main
    $result = & bin\emit_target_main.exe $irPath cpp $outputPath 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "emit_target_main failed: $result"
    }
    
    # Verify output
    if (-not (Test-Path $outputPath)) {
        throw "Output file not created: $outputPath"
    }
    
    $code = Get-Content $outputPath -Raw
    if (-not ($code -match "// Generated by STUNIR")) {
        throw "Output missing expected header"
    }
}

# Test 8: Emit Target (Rust)
Invoke-Test "emit_target_main - Emit Rust code" {
    $irPath = Join-Path $TestDir "test_ir.json"
    $outputPath = Join-Path $TestDir "output.rs"
    
    # Remove output if exists
    if (Test-Path $outputPath) { Remove-Item $outputPath -Force }
    
    # Run emit_target_main
    $result = & bin\emit_target_main.exe $irPath rust $outputPath 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "emit_target_main failed: $result"
    }
    
    # Verify output
    if (-not (Test-Path $outputPath)) {
        throw "Output file not created: $outputPath"
    }
    
    $code = Get-Content $outputPath -Raw
    if (-not ($code -match "// Generated by STUNIR")) {
        throw "Output missing expected header"
    }
}

# Test 9: Full Pipeline (spec_assembler_main)
Invoke-Test "spec_assembler_main - Full spec assembly" {
    $extractPath = Join-Path $TestDir "test_extract.json"
    $specPath = Join-Path $TestDir "pipeline_spec.json"
    
    # Remove output if exists
    if (Test-Path $specPath) { Remove-Item $specPath -Force }
    
    # Run spec_assembler_main
    $result = & bin\spec_assembler_main.exe $extractPath $specPath 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "spec_assembler_main failed: $result"
    }
    
    # Verify output
    if (-not (Test-Path $specPath)) {
        throw "Output file not created: $specPath"
    }
}

# Test 10: Full Pipeline (ir_converter_main)
Invoke-Test "ir_converter_main - Full IR conversion" {
    $specPath = Join-Path $TestDir "test_spec.json"
    $irPath = Join-Path $TestDir "pipeline_ir.json"
    
    # Remove output if exists
    if (Test-Path $irPath) { Remove-Item $irPath -Force }
    
    # Run ir_converter_main
    $result = & bin\ir_converter_main.exe $specPath $irPath 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "ir_converter_main failed: $result"
    }
    
    # Verify output
    if (-not (Test-Path $irPath)) {
        throw "Output file not created: $irPath"
    }
}

# Test 11: Full Pipeline (code_emitter_main)
Invoke-Test "code_emitter_main - Full code emission" {
    $irPath = Join-Path $TestDir "test_ir.json"
    $outputPath = Join-Path $TestDir "pipeline_output.py"
    
    # Remove output if exists
    if (Test-Path $outputPath) { Remove-Item $outputPath -Force }
    
    # Run code_emitter_main
    $result = & bin\code_emitter_main.exe $irPath python $outputPath 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "code_emitter_main failed: $result"
    }
    
    # Verify output
    if (-not (Test-Path $outputPath)) {
        throw "Output file not created: $outputPath"
    }
}

# Summary
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Test Summary" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Passed: $PassCount" -ForegroundColor Green
Write-Host "Failed: $FailCount" -ForegroundColor $(if ($FailCount -gt 0) { "Red" } else { "Green" })
Write-Host ""

# Cleanup output files
Write-Host "Cleaning up test outputs..." -ForegroundColor Yellow
$outputFiles = @(
    "output_extract.json",
    "output_spec.json",
    "output_ir.json",
    "output.py",
    "output.cpp",
    "output.rs",
    "pipeline_spec.json",
    "pipeline_ir.json",
    "pipeline_output.py"
)

foreach ($file in $outputFiles) {
    $filePath = Join-Path $TestDir $file
    if (Test-Path $filePath) {
        Remove-Item $filePath -Force
    }
}

if ($FailCount -gt 0) {
    exit 1
}
exit 0