// Generated by STUNIR Code Emitter
// DO NOT EDIT MANUALLY

pub fn main(a: i32) -> i32 {
    // step: assign target=b value=a
    // step: call target=c value=add(b, 1)
    // step: return value=c
    b = a;
    c = add(b, 1);
    return c;
}


