--  STUNIR AsmIr Emitter - Ada SPARK Specification
--  Assembly IR emitter (LLVM IR, custom IR formats)
--  DO-178C Level A compliant
--  Generated by: STUNIR Emitter Generator v1.0
--  Timestamp: 2026-01-31T02:44:19.170633Z

pragma SPARK_Mode (On);

with Emitter_Types; use Emitter_Types;

package AsmIr_Emitter is

   --  AsmIr target configuration
   type AsmIr_Config is record
      Ir_Format : String;
      Optimization_Level : Integer;
      Use_Ssa : Boolean;
   end record;

   --  Default configuration
   Default_Config : constant AsmIr_Config := (
      Ir_Format => llvm,
      Optimization_Level => 0,
      Use_Ssa => True
   );

   --  Main emission procedure with SPARK contracts
   procedure Emit_Module (
      Name      : in Identifier_String;
      Content   : out Content_String;
      Config    : in AsmIr_Config;
      Status    : out Emitter_Status)
      with Pre => Identifier_Strings.Length (Name) > 0,
           Post => (Status = Success) = (Content_Strings.Length (Content) > 0);

   --  Emit function code
   procedure Emit_Function (
      Func_Name : in Identifier_String;
      Params    : in String;
      Body_Code : in String;
      Content   : out Content_String;
      Status    : out Emitter_Status)
      with Pre => Identifier_Strings.Length (Func_Name) > 0;

   --  Type mapping from IR to AsmIr
   function Map_Type_To_ASM_IR (IR_Type : IR_Data_Type) return Type_Name_String;

end AsmIr_Emitter;
