#!/usr/bin/env python3
"""Tests for Systems Emitter.

Generated by: STUNIR Emitter Generator v1.0
"""

import unittest
import json
import tempfile
from pathlib import Path
from emitter import SystemsEmitter


class TestSystemsEmitter(unittest.TestCase):
    """Test suite for Systems emitter."""
    
    def setUp(self):
        """Set up test fixtures."""
        self.test_ir = {
            'module': 'test_module',
            'functions': [],
            'types': [],
        }
        self.temp_dir = tempfile.mkdtemp()
    
    def test_type_mapping(self):
        """Test IR type to Systems type mapping."""
        emitter = SystemsEmitter(self.test_ir, self.temp_dir)
        
        self.assertEqual(emitter._map_type('i32'), 'int32')
        self.assertEqual(emitter._map_type('bool'), 'boolean')
        self.assertEqual(emitter._map_type('string'), 'string')
    
    def test_emit_function(self):
        """Test function code generation."""
        emitter = SystemsEmitter(self.test_ir, self.temp_dir)
        
        code = emitter.emit_function('test_func', 'a, b', '    return a + b;')
        
        self.assertIn('function test_func', code)
        self.assertIn('return a + b', code)
    
    def test_emit_module(self):
        """Test module code generation."""
        emitter = SystemsEmitter(self.test_ir, self.temp_dir)
        
        code = emitter.emit_module('test_module')
        
        self.assertIn('STUNIR Generated', code)
        self.assertIn('test_module', code)
        self.assertIn('Python Pipeline', code)
    
    def test_run(self):
        """Test complete emission process."""
        emitter = SystemsEmitter(self.test_ir, self.temp_dir)
        
        manifest = emitter.run()
        
        self.assertEqual(manifest['category'], 'systems')
        self.assertEqual(manifest['generator'], 'python')
        self.assertGreater(len(manifest['files']), 0)


if __name__ == '__main__':
    unittest.main()
