#!/usr/bin/env bash
# scripts/lib/gen_provenance.sh
# Shell implementation of Provenance Generation.

stunir_shell_gen_provenance() {
    local epoch="0"
    local spec_root="spec"
    local asm_root="asm"
    local out_header=""
    local out_json=""

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --epoch) epoch="$2"; shift 2 ;;
            --spec-root) spec_root="$2"; shift 2 ;;
            --asm-root) asm_root="$2"; shift 2 ;;
            --out-header) out_header="$2"; shift 2 ;;
            --out-json) out_json="$2"; shift 2 ;;
            *) shift ;;
        esac
    done

    if [[ -z "$out_json" || -z "$out_header" ]]; then
        echo "Error: --out-json and --out-header required" >&2
        return 1
    fi

    mkdir -p "$(dirname "$out_json")"
    mkdir -p "$(dirname "$out_header")"

    # Helper: Hash Directory
    # We use a "Manifest Hash" strategy:
    # 1. List all files (sorted)
    # 2. Calculate hash of each file
    # 3. Hash the list of "filename hash" lines
    calc_dir_hash() {
        local dir="$1"
        if [[ ! -d "$dir" ]]; then
            echo "0000000000000000000000000000000000000000000000000000000000000000"
            return
        fi

        (
            cd "$dir"
            find . -type f | sort | while read -r f; do
                # Normalize path: ./foo -> foo
                local clean_path="${f#./}"

                # Calculate content hash
                local fhash=""
                if command -v sha256sum >/dev/null 2>&1; then
                    fhash=$(sha256sum "$f" | awk '{print $1}')
                else
                    fhash=$(shasum -a 256 "$f" | awk '{print $1}')
                fi

                # Output: "filename hash"
                echo "$clean_path $fhash"
            done
        ) | if command -v sha256sum >/dev/null 2>&1; then
            sha256sum | awk '{print $1}'
        else
            shasum -a 256 | awk '{print $1}'
        fi
    }

    local spec_digest=$(calc_dir_hash "$spec_root")
    local asm_digest=$(calc_dir_hash "$asm_root")

    # 1. JSON Output
    echo "{" > "$out_json"
    echo "  "build_epoch": $epoch," >> "$out_json"
    echo "  "epoch_source": "SHELL_DERIVED"," >> "$out_json"
    echo "  "spec_digest": "$spec_digest"," >> "$out_json"
    echo "  "asm_digest": "$asm_digest"," >> "$out_json"
    echo "  "provenance_version": 1" >> "$out_json"
    echo "}" >> "$out_json"

    # 2. C Header Output
    cat <<EOF > "$out_header"
/* AUTOGENERATED by scripts/lib/gen_provenance.sh */
#pragma once
#include <stdint.h>

#define STUNIR_PROV_BUILD_EPOCH $epoch
#define STUNIR_PROV_EPOCH_SOURCE "SHELL_DERIVED"
#define STUNIR_PROV_SPEC_DIGEST "$spec_digest"
#define STUNIR_PROV_ASM_DIGEST "$asm_digest"
EOF

    echo "Generated Provenance: $out_json"
}
