/* STUNIR Generated Code - Init Process
 * Module: init
 * Architecture: x86_64
 * DO-178C Level A Compliance
 */

#include "types.h"
#include "serial.h"
#include "pmm.h"
#include "timer.h"
#include "interrupts.h"
#include "syscalls.h"
#include "scheduler.h"

/* Init process entry point */
void init_main(void) {
    /* Print welcome message */
    sys_print("Hello, STUNIR OS!\n");
    
    /* Print some status */
    serial_write_string("Init process running...\n");
    serial_write_string("Free pages: ");
    serial_write_hex64(pmm_get_free_pages());
    serial_write_string("\n");
    
    /* Loop forever, yielding CPU */
    u32 count = 0;
    while (1) {
        sys_yield();
        count++;
        
        /* Print status every 100 yields */
        if (count % 100 == 0) {
            serial_write_string("Timer ticks: ");
            serial_write_hex64(timer_get_ticks());
            serial_write_string("\n");
        }
    }
}

/* Kernel main entry point (called from bootloader) */
void kernel_main(u32 magic, void* mboot_info) {
    (void)mboot_info;
    
    /* Initialize serial console first */
    serial_init();
    serial_write_string("\n=== STUNIR OS v0.1 ===\n");
    serial_write_string("Generated by STUNIR Multi-Model Workflow\n\n");
    
    /* Verify multiboot magic (optional - we may have lost it in long mode transition) */
    if (magic == 0x36D76289) {
        serial_write_string("[OK] Multiboot2 verified\n");
    } else {
        serial_write_string("[--] Multiboot magic: ");
        serial_write_hex(magic);
        serial_write_string(" (expected 0x36D76289)\n");
    }
    
    /* Initialize memory manager (128MB) */
    pmm_init(128 * 1024 * 1024);
    serial_write_string("[OK] Memory manager initialized (128MB)\n");
    serial_write_string("     Free pages: ");
    serial_write_hex64(pmm_get_free_pages());
    serial_write_string("\n");
    
    /* Initialize interrupts */
    idt_init();
    serial_write_string("[OK] IDT initialized\n");
    
    /* Initialize timer at 100Hz */
    timer_init(100);
    serial_write_string("[OK] Timer initialized (100Hz)\n");
    
    /* Initialize syscalls */
    syscall_init();
    serial_write_string("[OK] Syscalls initialized\n");
    
    /* Initialize scheduler */
    scheduler_init();
    serial_write_string("[OK] Scheduler initialized\n");
    
    /* Enable interrupts */
    __asm__ volatile ("sti");
    serial_write_string("[OK] Interrupts enabled\n\n");
    
    /* Create init task */
    i32 tid = task_create(init_main, "init");
    if (tid >= 0) {
        serial_write_string("Starting init process (task ");
        serial_write_hex(tid);
        serial_write_string(")...\n\n");
    } else {
        serial_write_string("ERROR: Failed to create init task!\n");
        while (1) {
            __asm__ volatile ("hlt");
        }
    }
    
    /* Start scheduler - never returns */
    scheduler_running = 1;
    start_first_task();
    
    /* Should never reach here */
    serial_write_string("ERROR: Scheduler returned!\n");
    while (1) {
        __asm__ volatile ("hlt");
    }
}
