#!/usr/bin/env python3
"""Generate refined Go outputs from IR manifests."""

from __future__ import annotations
import argparse, json
from pathlib import Path

def _w(p: Path, s: str) -> None:
    """Write text to a file path, creating parent directories as needed."""
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(s, encoding="utf-8", newline="\n")

def main() -> int:
    """Read an IR manifest and emit Go files and scaffolding."""
    ap = argparse.ArgumentParser()
    ap.add_argument("--variant", required=True)
    ap.add_argument("--ir-manifest", required=True)
    ap.add_argument("--out-root", required=True)
    args = ap.parse_args()

    out_root = Path(args.out_root)
    ir = json.loads(Path(args.ir_manifest).read_text(encoding="utf-8"))

    # 1. Scaffolding
    _w(out_root / "go.mod", "module stunir_generated\n\ngo 1.20\n")

    # 2. Modules
    modules = ir.get("modules", [])

    if not modules:
        _w(out_root / "main.go", """package main
import "fmt"
func main() { fmt.Println("Hello from Refined Go (No Modules)") }
""")
    else:
        # For simplicity, put everything in main package for now, or separate files
        # If code is raw Go, we assume it has package decl. If not, we prepend it.
        for mod in modules:
            name = mod.get("name", "main")
            code = mod.get("code", "// Empty")
            if "package " not in code:
                code = "package main\n\n" + code
            _w(out_root / f"{name}.go", code)

    _w(out_root / "README.md", "# Go Artifact\nGenerated by STUNIR Refined Generator")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
