#!/usr/bin/env python3
"""Generate refined Haskell outputs from IR manifests."""

from __future__ import annotations
import argparse, json
from pathlib import Path

def _w(p: Path, s: str) -> None:
    """Write text to a file path, creating parent directories as needed."""
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(s, encoding="utf-8", newline="\n")

def main() -> int:
    """Read an IR manifest and emit Haskell files and a build script."""
    ap = argparse.ArgumentParser()
    ap.add_argument("--variant", required=True)
    ap.add_argument("--ir-manifest", required=True)
    ap.add_argument("--out-root", required=True)
    args = ap.parse_args()

    out_root = Path(args.out_root)
    ir = json.loads(Path(args.ir_manifest).read_text(encoding="utf-8"))

    modules = ir.get("modules", [])

    # Emit modules
    for mod in modules:
        name = mod.get("name", "program")
        code = mod.get("code", "")
        ext = "hs"
        _w(out_root / f"{name}.{ext}", code)

    # Emit Build Script (Mock)
    _w(out_root / "build.sh", "#!/bin/bash\necho 'Building Haskell project...'")

    _w(out_root / "README.md", "# Haskell Artifact\nGenerated by STUNIR Refined Generator")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
