#!/usr/bin/env python3
"""Generate refined Python outputs from IR manifests."""

from __future__ import annotations
import argparse, json
from pathlib import Path

def _w(p: Path, s: str) -> None:
    """Write text to a file path, creating parent directories as needed."""
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(s, encoding="utf-8", newline="\n")

def main() -> int:
    """Read an IR manifest and emit Python files and scaffolding."""
    ap = argparse.ArgumentParser()
    ap.add_argument("--variant", required=True)
    ap.add_argument("--ir-manifest", required=True)
    ap.add_argument("--out-root", required=True)
    args = ap.parse_args()

    out_root = Path(args.out_root)
    ir = json.loads(Path(args.ir_manifest).read_text(encoding="utf-8"))

    # 1. Scaffolding
    _w(out_root / "pyproject.toml", """[project]
name = "stunir_generated"
version = "0.1.0"
description = "Generated by STUNIR"
dependencies = []
""")

    # 2. Modules
    src_dir = out_root / "src"
    _w(src_dir / "__init__.py", "")

    modules = ir.get("modules", [])
    if not modules:
        # Fallback if no modules
        _w(src_dir / "main.py", "print('Hello from Refined Python (No Modules)')")
    else:
        for mod in modules:
            name = mod.get("name", "mod")
            code = mod.get("code", f"# Code for {name}")
            _w(src_dir / f"{name}.py", code)

    _w(out_root / "README.md", "# Python Artifact\nGenerated by STUNIR Refined Generator")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
