{-# LANGUAGE OverloadedStrings #-}

-- | Beam code emitter
--
-- Erlang BEAM VM emitter (Erlang, Elixir source and bytecode)
--
-- Generated by: STUNIR Emitter Generator v1.0
-- Timestamp: 2026-01-31T02:44:19.366736Z
module STUNIR.Emitters.Beam
  ( emitBeam
  , BeamConfig(..)
  ) where

import Data.Text (Text)
import qualified Data.Text as T
import STUNIR.Emitters.Types

-- | Beam configuration
data BeamConfig = BeamConfig
  { configIndent :: Int
  , configValidate :: Bool
  } deriving (Show, Eq)

-- | Default configuration
defaultBeamConfig :: BeamConfig
defaultBeamConfig = BeamConfig
  { configIndent = 2
  , configValidate = True
  }

-- | Map IR type to Beam type
mapIRType :: Text -> Text
mapIRType "i32" = "int32"
mapIRType "i64" = "int64"
mapIRType "f32" = "float"
mapIRType "f64" = "double"
mapIRType "bool" = "boolean"
mapIRType "string" = "string"
mapIRType _ = "int32"

-- | Emit function code
emitFunction :: Text -> Text -> Text -> Text
emitFunction funcName params body = T.unlines
  [ "function " <> funcName <> "(" <> params <> ") {"
  , body
  , "}"
  ]

-- | Emit Beam module
emitBeam :: Text -> BeamConfig -> EmitterResult Text
emitBeam moduleName config = Right $ T.unlines $
  [ "/* STUNIR Generated Beam Code */"
  , "/* Module: " <> moduleName <> " */"
  , "/* Generator: Haskell Pipeline */"
  , ""
  ] ++ moduleBody
  where
    moduleBody =
      [ "// Beam implementation goes here"
      ]
