{-# LANGUAGE OverloadedStrings #-}

-- | Grammar code emitter
--
-- Grammar definition emitter (ANTLR, Yacc, PEG, EBNF)
--
-- Generated by: STUNIR Emitter Generator v1.0
-- Timestamp: 2026-01-31T02:44:18.173801Z
module STUNIR.Emitters.Grammar
  ( emitGrammar
  , GrammarConfig(..)
  ) where

import Data.Text (Text)
import qualified Data.Text as T
import STUNIR.Emitters.Types

-- | Grammar configuration
data GrammarConfig = GrammarConfig
  { configIndent :: Int
  , configValidate :: Bool
  } deriving (Show, Eq)

-- | Default configuration
defaultGrammarConfig :: GrammarConfig
defaultGrammarConfig = GrammarConfig
  { configIndent = 2
  , configValidate = True
  }

-- | Map IR type to Grammar type
mapIRType :: Text -> Text
mapIRType "i32" = "int32"
mapIRType "i64" = "int64"
mapIRType "f32" = "float"
mapIRType "f64" = "double"
mapIRType "bool" = "boolean"
mapIRType "string" = "string"
mapIRType _ = "int32"

-- | Emit function code
emitFunction :: Text -> Text -> Text -> Text
emitFunction funcName params body = T.unlines
  [ "function " <> funcName <> "(" <> params <> ") {"
  , body
  , "}"
  ]

-- | Emit Grammar module
emitGrammar :: Text -> GrammarConfig -> EmitterResult Text
emitGrammar moduleName config = Right $ T.unlines $
  [ "/* STUNIR Generated Grammar Code */"
  , "/* Module: " <> moduleName <> " */"
  , "/* Generator: Haskell Pipeline */"
  , ""
  ] ++ moduleBody
  where
    moduleBody =
      [ "// Grammar implementation goes here"
      ]
