{-# LANGUAGE OverloadedStrings #-}

-- | Json code emitter
--
-- JSON serialization and deserialization emitter
--
-- Generated by: STUNIR Emitter Generator v1.0
-- Timestamp: 2026-01-31T02:35:20.939899Z
module STUNIR.Emitters.Json
  ( emitJson
  , JsonConfig(..)
  ) where

import Data.Text (Text)
import qualified Data.Text as T
import STUNIR.Emitters.Types

-- | Json configuration
data JsonConfig = JsonConfig
  { configIndent :: Int
  , configValidate :: Bool
  } deriving (Show, Eq)

-- | Default configuration
defaultJsonConfig :: JsonConfig
defaultJsonConfig = JsonConfig
  { configIndent = 2
  , configValidate = True
  }

-- | Map IR type to Json type
mapIRType :: Text -> Text
mapIRType "i32" = "int32"
mapIRType "i64" = "int64"
mapIRType "f32" = "float"
mapIRType "f64" = "double"
mapIRType "bool" = "boolean"
mapIRType "string" = "string"
mapIRType _ = "int32"

-- | Emit function code
emitFunction :: Text -> Text -> Text -> Text
emitFunction funcName params body = T.unlines
  [ "function " <> funcName <> "(" <> params <> ") {"
  , body
  , "}"
  ]

-- | Emit Json module
emitJson :: Text -> JsonConfig -> EmitterResult Text
emitJson moduleName config = Right $ T.unlines $
  [ "/* STUNIR Generated Json Code */"
  , "/* Module: " <> moduleName <> " */"
  , "/* Generator: Haskell Pipeline */"
  , ""
  ] ++ moduleBody
  where
    moduleBody =
      [ "// Json implementation goes here"
      ]
