--  STUNIR Polyglot Emitter - Ada SPARK Specification
--  Polyglot emitter (C89, C99, Rust)
--  DO-178C Level A compliant
--  Generated by: STUNIR Emitter Generator v1.0
--  Timestamp: 2026-02-04T12:19:49.334745Z

pragma SPARK_Mode (On);

with Emitter_Types; use Emitter_Types;

package Polyglot_Emitter is

   --  Polyglot target configuration
   type Polyglot_Config is record
      Target_Dialect : String;
   end record;

   --  Default configuration
   Default_Config : constant Polyglot_Config := (
      Target_Dialect => c99
   );

   --  Main emission procedure with SPARK contracts
   procedure Emit_Module (
      Name      : in Identifier_String;
      Content   : out Content_String;
      Config    : in Polyglot_Config;
      Status    : out Emitter_Status)
      with Pre => Identifier_Strings.Length (Name) > 0,
           Post => (Status = Success) = (Content_Strings.Length (Content) > 0);

   --  Emit function code
   procedure Emit_Function (
      Func_Name : in Identifier_String;
      Params    : in String;
      Body_Code : in String;
      Content   : out Content_String;
      Status    : out Emitter_Status)
      with Pre => Identifier_Strings.Length (Func_Name) > 0;

   --  Type mapping from IR to Polyglot
   function Map_Type_To_POLYGLOT (IR_Type : IR_Data_Type) return Type_Name_String;

end Polyglot_Emitter;
