/* STUNIR Generated Code
 * Generated by: stunir_ir_to_code_spark v0.7.1
 * Module: spec_to_ir
 */

#include <stdint.h>
#include <stdbool.h>

uint16_t crc_crc4(uint16_t * data) {
    /* TODO: Implement */
    return 0;
}

uint8_t crc_crc8(const uint8_t * p,  uint8_t len) {
    /* TODO: Implement */
    return 0;
}

uint8_t crc8_generic(const uint8_t * buf,  const uint16_t buf_len,  const uint8_t polynomial,  uint8_t initial_value) {
    /* TODO: Implement */
    return 0;
}

uint8_t crc8_dvb_s2(uint8_t crc,  uint8_t a) {
    /* TODO: Implement */
    return 0;
}

uint8_t crc8_dvb(uint8_t crc,  uint8_t a,  uint8_t seed) {
    /* TODO: Implement */
    return 0;
}

uint8_t crc8_dvb_s2_update(uint8_t crc,  const void * data,  uint32_t length) {
    /* TODO: Implement */
    return 0;
}

uint8_t crc8_dvb_update(uint8_t crc,  const uint8_t* buf,  const uint16_t buf_len) {
    /* TODO: Implement */
    return 0;
}

uint8_t crc8_maxim(const uint8_t * data,  uint16_t length) {
    /* TODO: Implement */
    return 0;
}

uint8_t crc8_sae(const uint8_t * data,  uint16_t length) {
    /* TODO: Implement */
    return 0;
}

uint8_t crc8_rds02uf(const uint8_t * data,  uint16_t length) {
    /* TODO: Implement */
    return 0;
}

uint16_t crc_xmodem_update(uint16_t crc,  uint8_t data) {
    /* TODO: Implement */
    return 0;
}

uint16_t crc_xmodem(const uint8_t * data,  uint16_t len) {
    /* TODO: Implement */
    return 0;
}

uint32_t crc32_small(uint32_t crc,  const uint8_t * buf,  uint32_t size) {
    /* TODO: Implement */
    return 0;
}

uint16_t crc16_ccitt(const uint8_t * buf,  uint32_t len,  uint16_t crc) {
    /* TODO: Implement */
    return 0;
}

uint16_t crc16_ccitt_r(const uint8_t * buf,  uint32_t len,  uint16_t crc,  uint16_t out) {
    /* TODO: Implement */
    return 0;
}

uint16_t crc16_ccitt_GDL90(const uint8_t * buf,  uint32_t len,  uint16_t crc) {
    /* TODO: Implement */
    return 0;
}

uint16_t calc_crc_modbus(const uint8_t * buf,  uint16_t len) {
    /* TODO: Implement */
    return 0;
}

uint16_t crc_fletcher16(const uint8_t * buffer,  uint32_t len) {
    /* TODO: Implement */
    return 0;
}

void hash_fnv_1a(uint32_t len,  const uint8_t* buf,  uint64_t* hash) {
    /* TODO: Implement */
    return;
}

uint32_t crc_crc24q(const uint8_t * bytes,  uint16_t len) {
    /* TODO: Implement */
    return 0;
}

