;; Generated by STUNIR
;; Module: control_flow_test
(define (simple_return x)
  x
)

(define (simple_assign a b)
  (set! result a + b)
  result
)

(define (if_else_test x)
  (if x > 0
    (begin
      x
    )
    (begin
      -x
    )
  )
)

(define (nested_if_test a b)
  (if a > b
    (begin
      (set! max a)
    )
    (begin
      (set! max b)
    )
  )
  max
)

(define (while_loop_test n)
  (set! sum 0)
  (set! i 1)
  (let loop ()
    (when i <= n
      (set! sum sum + i)
      (set! i i + 1)
      (loop))
    )
  )
  sum
)

(define (for_loop_test n)
  (set! factorial 1)
  ;; for loop: use named let or do
  ;   (set! factorial factorial * i)
  factorial
)

(define (mixed_control_flow arr len)
  (set! sum 0)
  (set! i 0)
  (let loop ()
    (when i < len
      (set! sum sum + arr[i])
      (set! i i + 1)
      (loop))
    )
  )
  sum
)

(define (call_test x)
  (set! result (simple_return x))
  result
)

;; End of module

