-- Generated by STUNIR
-- Module: control_flow_test
def simple_return (x : int) : int :=
  x

def simple_assign (a : int) (b : int) : int :=
  let result := a + b
  result

def if_else_test (x : int) : int :=
  if x > 0 then x else -x

def nested_if_test (a : int) (b : int) : int :=
  let max := if a > b then a else b
  max

def while_loop_test (n : int) : int :=
  let sum := 0
  let i := 1
  -- while i <= n (use forM or recursion)
  --   let sum := sum + i
  --   let i := i + 1
  sum

def for_loop_test (n : int) : int :=
  let factorial := 1
  -- for i = 1; i <= n; i++
  --   let factorial := factorial * i
  factorial

def mixed_control_flow (arr : int[]) (len : int) : int :=
  let sum := 0
  let i := 0
  -- while i < len (use forM or recursion)
  --   let sum := sum + arr[i]
  --   let i := i + 1
  sum

def call_test (x : int) : int :=
  let result := simple_return x
  result

-- End of module

