% Generated by STUNIR
% Module: control_flow_test
% simple_return(int)
simple_return(x, Result) :-
    Result = x.

% simple_assign(int)
simple_assign(a, b, Result) :-
    result is a + b,
    Result = result.

% if_else_test(int)
if_else_test(x, Result) :-
    (x > 0 ->
        Result = x
    ; 
        Result = -x
    ),

% nested_if_test(int)
nested_if_test(a, b, Result) :-
    (a > b ->
        max is a,
    ; 
        max is b,
    ),
    Result = max.

% while_loop_test(int)
while_loop_test(n, Result) :-
    sum is 0,
    i is 1,
    % while loop: use recursion
    % condition: i <= n
    %   sum is sum + i
    %   i is i + 1
    Result = sum.

% for_loop_test(int)
for_loop_test(n, Result) :-
    factorial is 1,
    % for loop: use recursion or between/3
    %   factorial is factorial * i
    Result = factorial.

% mixed_control_flow(int)
mixed_control_flow(arr, len, Result) :-
    sum is 0,
    i is 0,
    % while loop: use recursion
    % condition: i < len
    %   sum is sum + arr[i]
    %   i is i + 1
    Result = sum.

% call_test(int)
call_test(x, Result) :-
    simple_return(x, result),
    Result = result.

% End of module

