--  STUNIR Oop Emitter - Ada SPARK Specification
--  Object-oriented emitter
--  DO-178C Level A compliant
--  Generated by: STUNIR Emitter Generator v1.0
--  Timestamp: 2026-02-04T12:19:33.334897Z

pragma SPARK_Mode (On);

with Emitter_Types; use Emitter_Types;

package Oop_Emitter is

   --  Oop target configuration
   type Oop_Config is record
      Target_Language : String;
   end record;

   --  Default configuration
   Default_Config : constant Oop_Config := (
      Target_Language => java
   );

   --  Main emission procedure with SPARK contracts
   procedure Emit_Module (
      Name      : in Identifier_String;
      Content   : out Content_String;
      Config    : in Oop_Config;
      Status    : out Emitter_Status)
      with Pre => Identifier_Strings.Length (Name) > 0,
           Post => (Status = Success) = (Content_Strings.Length (Content) > 0);

   --  Emit function code
   procedure Emit_Function (
      Func_Name : in Identifier_String;
      Params    : in String;
      Body_Code : in String;
      Content   : out Content_String;
      Status    : out Emitter_Status)
      with Pre => Identifier_Strings.Length (Func_Name) > 0;

   --  Type mapping from IR to Oop
   function Map_Type_To_OOP (IR_Type : IR_Data_Type) return Type_Name_String;

end Oop_Emitter;
