--  code_gen_preamble - Generate code preamble (imports, headers)
--  Input:  --target LANG flag
--  Output: Language-appropriate preamble code (stdout)

pragma SPARK_Mode (Off);

with Ada.Command_Line;
with Ada.Text_IO;
with Ada.Strings.Unbounded;
with GNAT.Strings;
with GNAT.Command_Line;

procedure Code_Gen_Preamble is
   use Ada.Command_Line;
   use Ada.Text_IO;
   use Ada.Strings.Unbounded;

   Exit_Success : constant := 0;
   Exit_Error   : constant := 1;

   Target_Lang   : aliased GNAT.Strings.String_Access := new String'("");
   Mod_Name      : aliased GNAT.Strings.String_Access := new String'("generated");
   Show_Version  : aliased Boolean := False;
   Show_Help     : aliased Boolean := False;
   Show_Describe : aliased Boolean := False;

   Version : constant String := "0.1.0-alpha";

   Describe_Output : constant String :=
     "{""tool"":""code_gen_preamble"",""version"":""0.1.0-alpha""," &
     """description"":""Generate code preamble for target language""," &
     """inputs"":[{""type"":""flag"",""name"":""--target"",""required"":true}]," &
     """outputs"":[{""type"":""code"",""source"":""stdout""}]," &
     """options"":[""--target LANG"",""--module NAME""]," &
     """targets"":[""c"",""cpp"",""rust"",""python"",""js"",""go""]}";

   function Gen_Preamble (Lang : String; Module : String) return String is
      R : Unbounded_String;
   begin
      if Lang = "c" then
         Append (R, "#include <stdint.h>" & ASCII.LF);
         Append (R, "#include <stdbool.h>" & ASCII.LF);
         Append (R, "#include <string.h>" & ASCII.LF);
         Append (R, "#include <stdlib.h>");
      elsif Lang = "cpp" then
         Append (R, "#include <cstdint>" & ASCII.LF);
         Append (R, "#include <string>" & ASCII.LF);
         Append (R, "#include <vector>" & ASCII.LF);
         Append (R, "#include <cstring>");
      elsif Lang = "rust" then
         Append (R, "//! Generated by STUNIR" & ASCII.LF);
         Append (R, "#![allow(unused_variables, dead_code)]");
      elsif Lang = "python" then
         Append (R, "#!/usr/bin/env python3" & ASCII.LF);
         Append (R, "from typing import Optional, List");
      elsif Lang = "js" or Lang = "javascript" then
         Append (R, "// Generated by STUNIR" & ASCII.LF);
         Append (R, "'use strict';");
      elsif Lang = "go" then
         Append (R, "package " & Module & ASCII.LF);
         Append (R, "" & ASCII.LF);
         Append (R, "import ()");
      else
         return "";
      end if;
      return To_String (R);
   end Gen_Preamble;

   Config : GNAT.Command_Line.Command_Line_Configuration;

begin
   GNAT.Command_Line.Define_Switch (Config, Show_Help'Access,    "-h", "--help");
   GNAT.Command_Line.Define_Switch (Config, Show_Version'Access, "-v", "--version");
   GNAT.Command_Line.Define_Switch (Config, Show_Describe'Access, "", "--describe");
   GNAT.Command_Line.Define_Switch (Config, Target_Lang'Access,  "-t:", "--target=");
   GNAT.Command_Line.Define_Switch (Config, Mod_Name'Access,     "-m:", "--module=");

   begin
      GNAT.Command_Line.Getopt (Config);
   exception
      when others =>
         Put_Line (Standard_Error, "ERROR: Invalid arguments");
         Set_Exit_Status (Exit_Error); return;
   end;

   if Show_Help then
      Put_Line ("code_gen_preamble - Generate code preamble for target language");
      Put_Line ("Version: " & Version);
      New_Line;
      Put_Line ("Usage: code_gen_preamble --target LANG");
      Put_Line ("  --target LANG   Target language: c cpp rust python js go");
      Put_Line ("  --module NAME   Module/package name (used by Go)");
      Set_Exit_Status (Exit_Success); return;
   end if;
   if Show_Version then
      Put_Line ("code_gen_preamble " & Version);
      Set_Exit_Status (Exit_Success); return;
   end if;
   if Show_Describe then
      Put_Line (Describe_Output);
      Set_Exit_Status (Exit_Success); return;
   end if;

   if Target_Lang.all = "" then
      Put_Line (Standard_Error, "ERROR: --target LANG required");
      Set_Exit_Status (Exit_Error); return;
   end if;

   declare
      Preamble : constant String := Gen_Preamble (Target_Lang.all, Mod_Name.all);
   begin
      if Preamble'Length = 0 then
         Put_Line (Standard_Error, "ERROR: Unsupported target: " & Target_Lang.all);
         Set_Exit_Status (Exit_Error); return;
      end if;
      Put_Line (Preamble);
      Set_Exit_Status (Exit_Success);
   end;

exception
   when others =>
      Put_Line (Standard_Error, "ERROR: Processing failed");
      Set_Exit_Status (Exit_Error);
end Code_Gen_Preamble;
