--  STUNIR Grammar Emitter - Ada SPARK Specification
--  Grammar definition emitter (ANTLR, Yacc, PEG, EBNF)
--  DO-178C Level A compliant
--  Generated by: STUNIR Emitter Generator v1.0
--  Timestamp: 2026-01-31T02:44:18.173801Z

pragma SPARK_Mode (On);

with Emitter_Types; use Emitter_Types;

package Grammar_Emitter is

   --  Grammar target configuration
   type Grammar_Config is record
      Format : String;
      Generate_Ast : Boolean;
      Target_Language : String;
   end record;

   --  Default configuration
   Default_Config : constant Grammar_Config := (
      Format => antlr,
      Generate_Ast => True,
      Target_Language => python
   );

   --  Main emission procedure with SPARK contracts
   procedure Emit_Module (
      Name      : in Identifier_String;
      Content   : out Content_String;
      Config    : in Grammar_Config;
      Status    : out Emitter_Status)
      with Pre => Identifier_Strings.Length (Name) > 0,
           Post => (Status = Success) = (Content_Strings.Length (Content) > 0);

   --  Emit function code
   procedure Emit_Function (
      Func_Name : in Identifier_String;
      Params    : in String;
      Body_Code : in String;
      Content   : out Content_String;
      Status    : out Emitter_Status)
      with Pre => Identifier_Strings.Length (Func_Name) > 0;

   --  Type mapping from IR to Grammar
   function Map_Type_To_GRAMMAR (IR_Type : IR_Data_Type) return Type_Name_String;

end Grammar_Emitter;
