#!/usr/bin/env python3
import argparse
import json
from pathlib import Path

def _read_epoch_from_epoch_json(spec_root: str | None) -> str | int | None:
    candidates = []
    if spec_root:
        candidates.append(Path(spec_root) / "epoch.json")
    candidates.append(Path("build/epoch.json"))
    for c in candidates:
        if c.exists():
            try:
                obj = json.loads(c.read_text(encoding="utf-8"))
                if "selected_epoch" in obj:
                    return obj["selected_epoch"]
            except Exception:
                pass
    return None

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--epoch", default=None)
    ap.add_argument("--epoch-source", default=None)
    ap.add_argument("--spec-root", default=None)
    ap.add_argument("--asm-root", default=None)
    ap.add_argument("--out-header", default=None)
    ap.add_argument("--out-json", default=None)

    # legacy flags still accepted
    ap.add_argument("--in-ir", dest="in_ir", default=None)
    ap.add_argument("--out-prov", dest="out_prov", default=None)

    args = ap.parse_args()

    out_json = args.out_json or args.out_prov or "build/provenance.json"
    out_header = args.out_header

    epoch_val = args.epoch
    if epoch_val is None:
        epoch_val = _read_epoch_from_epoch_json(args.spec_root)

    try:
        epoch_int = int(epoch_val) if epoch_val is not None else 0
    except Exception:
        epoch_int = 0

    prov = {
        "build_epoch": epoch_int
    }

    Path(out_json).write_text(
        json.dumps(prov, sort_keys=True, separators=(",", ":")) + "\n",
        encoding="utf-8"
    )

    if out_header:
        Path(out_header).write_text(
            "// generated by tools/gen_provenance.py\n"
            "#pragma once\n"
            f"#define STUNIR_BUILD_EPOCH {epoch_int}\n",
            encoding="utf-8"
        )

    print("Generated Provenance")

if __name__ == "__main__":
    main()
