#!/usr/bin/env python3
"""Generate provenance metadata.

Outputs:
- JSON provenance (`--out-json`) with digests of spec/ and asm/
- A tiny C header (`--out-header`) used by tools/prov_emit.c

This file must be deterministic: same inputs => same outputs.
"""

import argparse
import hashlib
import json
import os
from pathlib import Path


def sha256_of_dir(root: Path) -> str:
    """Deterministic directory digest: sha256 over (relpath + bytes) in sorted traversal."""
    if not root.exists():
        return '0' * 64
    h = hashlib.sha256()
    for p in sorted(root.rglob('*')):
        if p.is_file():
            h.update(p.relative_to(root).as_posix().encode('utf-8'))
            with p.open('rb') as f:
                for chunk in iter(lambda: f.read(1024 * 1024), b''):
                    h.update(chunk)
    return h.hexdigest()


def write_c_header(path: Path, build_epoch: int, spec_digest: str, asm_digest: str, epoch_source: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    header = (
        '/* AUTOGENERATED by tools/gen_provenance.py. */
'
        '#pragma once
'
        '#include <stdint.h>
'
        '
'
        f'#define STUNIR_PROV_BUILD_EPOCH {int(build_epoch)}
'
        f'#define STUNIR_PROV_EPOCH_SOURCE "{epoch_source}"
'
        f'#define STUNIR_PROV_SPEC_DIGEST "{spec_digest}"
'
        f'#define STUNIR_PROV_ASM_DIGEST "{asm_digest}"
'
    )
    path.write_text(header, encoding='utf-8')


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--epoch', required=True)
    parser.add_argument('--epoch-source', default='UNKNOWN')
    parser.add_argument('--spec-root', default='spec')
    parser.add_argument('--asm-root', default='asm')
    parser.add_argument('--out-header', required=True)
    parser.add_argument('--out-json', required=True)
    args = parser.parse_args()

    spec_root = Path(args.spec_root)
    asm_root = Path(args.asm_root)

    spec_digest = sha256_of_dir(spec_root)
    asm_digest = sha256_of_dir(asm_root)

    try:
        epoch = int(str(args.epoch).strip())
    except Exception:
        epoch = 0

    meta = {
        'build_epoch': epoch,
        'epoch_source': args.epoch_source,
        'spec_digest': spec_digest,
        'asm_digest': asm_digest,
        'provenance_version': 1,
    }

    out_json = Path(args.out_json)
    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_json.write_text(
        json.dumps(meta, sort_keys=True, separators=(',', ':'), ensure_ascii=False) + '
',
        encoding='utf-8',
    )

    write_c_header(Path(args.out_header), epoch, spec_digest, asm_digest, str(args.epoch_source))


if __name__ == '__main__':
    main()
