#!/usr/bin/env python3
"""Generate minimal deterministic SMT2 outputs from an IR manifest."""
from __future__ import annotations
import argparse, json, hashlib
from pathlib import Path
from typing import Any

def sha256_bytes(b: bytes) -> str:
    """Compute a SHA-256 digest for bytes."""
    return hashlib.sha256(b).hexdigest()

def canonical_json_bytes(obj: Any) -> bytes:
    """Serialize an object to canonical JSON bytes with a trailing newline."""
    return (json.dumps(obj, sort_keys=True, separators=(",", ":"), ensure_ascii=False) + '\n').encode('utf-8')

def write_text(p: Path, s: str) -> None:
    """Write text to a file path, creating parent directories as needed."""
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(s, encoding='utf-8', newline='\n')

def main() -> None:
    """Emit a minimal SMT2 problem from an IR manifest."""
    ap = argparse.ArgumentParser()
    ap.add_argument('--variant', required=True)
    ap.add_argument('--ir-manifest', required=True)
    ap.add_argument('--out-root', required=True)
    args = ap.parse_args()
    out_root = Path(args.out_root)
    ir_manifest = json.loads(Path(args.ir_manifest).read_text(encoding='utf-8'))
    ir_sha = sha256_bytes(canonical_json_bytes(ir_manifest))
    smt = ''.join([
        f'; Generated by STUNIR (SMT2 backend, minimal)\n',
        f'; IR manifest sha256: {ir_sha}\n\n',
        '(set-logic QF_UF)\n',
        '(declare-fun a () Bool)\n',
        '(assert a)\n',
        '(check-sat)\n',
    ])
    write_text(out_root/'problem.smt2', smt)
    write_text(out_root/'README.md', 'SMT2 portable output (minimal sample).\n')
if __name__ == '__main__':
    main()
