#!/usr/bin/env python3
"""Emit deterministic JVM (Java) hosted-runtime artifacts from the IR manifest.

V0 semantics: minimal introspection/stub (no JSON parsing deps).
"""

import argparse
import json
from pathlib import Path


def load_ir_manifest(path: Path) -> dict:
    obj = json.loads(path.read_text(encoding='utf-8'))
    if not isinstance(obj, dict) or obj.get('schema') not in ('stunir.ir_manifest.v2',):
        raise SystemExit(f'Unexpected IR manifest schema in {path}: {obj.get("schema")!r}')
    return obj


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding='utf-8', newline='
')


def gen_main_java() -> str:
    return """// Generated by STUNIR (java backend, v0)

import java.nio.file.*;
import java.security.MessageDigest;

public class Main {
  static String toHex(byte[] b) {
    StringBuilder sb = new StringBuilder();
    for (byte x : b) sb.append(String.format("%02x", x));
    return sb.toString();
  }

  static String sha256(Path p) throws Exception {
    MessageDigest md = MessageDigest.getInstance("SHA-256");
    byte[] data = Files.readAllBytes(p);
    md.update(data);
    return toHex(md.digest());
  }

  static Path findRepoRoot(Path start) {
    Path cur = start.toAbsolutePath().normalize();
    for (int i = 0; i < 16; i++) {
      Path irm = cur.resolve("receipts").resolve("ir_manifest.json");
      Path irdir = cur.resolve("asm").resolve("ir");
      if (Files.exists(irm) && Files.exists(irdir)) return cur;
      Path parent = cur.getParent();
      if (parent == null) break;
      cur = parent;
    }
    throw new RuntimeException("Could not locate repo root from " + start);
  }

  public static void main(String[] args) throws Exception {
    Path here = Paths.get(".").toAbsolutePath().normalize();
    Path repo = findRepoRoot(here);
    Path irManifest = repo.resolve("receipts").resolve("ir_manifest.json");
    long bytesLen = Files.size(irManifest);
    String sha = sha256(irManifest);

    String out = "{"
      + "\"schema\":\"stunir.java_sample_run.v0\","
      + "\"variant\":\"hosted\","
      + "\"ir_manifest_sha256\":\"" + sha + "\","
      + "\"ir_manifest_bytes_len\":" + bytesLen
      + "}";
    System.out.println(out);
  }
}
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument('--variant', required=True, choices=['hosted'])
    ap.add_argument('--ir-manifest', required=True)
    ap.add_argument('--out-root', required=True)
    args = ap.parse_args()

    _ = load_ir_manifest(Path(args.ir_manifest))

    out_root = Path(args.out_root)
    out_root.mkdir(parents=True, exist_ok=True)

    write_text(out_root / 'Main.java', gen_main_java())

    readme = """# STUNIR JVM target (hosted)

This directory is generated.

- `Main.java` prints a deterministic JSON summary bound to `receipts/ir_manifest.json`.

Run (Java 11+ source-file mode), from repo root:
- `cd asm/java/app && java Main.java`
"""
    write_text(out_root / 'README.md', readme)


if __name__ == '__main__':
    main()
