#!/usr/bin/env python3
"""Emit deterministic Node.js hosted-runtime artifacts from the IR manifest.

V0 semantics: introspection/stub.
"""

import argparse
import json
from pathlib import Path


def load_ir_manifest(path: Path) -> dict:
    obj = json.loads(path.read_text(encoding='utf-8'))
    if not isinstance(obj, dict) or obj.get('schema') not in ('stunir.ir_manifest.v2',):
        raise SystemExit(f'Unexpected IR manifest schema in {path}: {obj.get("schema")!r}')
    return obj


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding='utf-8', newline='
')


def gen_package_json() -> str:
    obj = {
        'name': 'stunir-node-app',
        'version': '0.0.0',
        'private': True,
        'description': 'Generated by STUNIR (node backend, v0)',
        'main': 'index.js',
        'scripts': {'start': 'node index.js'},
    }
    return json.dumps(obj, ensure_ascii=False, sort_keys=True, separators=(',', ':')) + "
"


def gen_index_js() -> str:
    return """// Generated by STUNIR (node backend, v0)

'use strict';

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

function sha256File(p) {
  const b = fs.readFileSync(p);
  return crypto.createHash('sha256').update(b).digest('hex');
}

function findRepoRoot(startDir) {
  let cur = path.resolve(startDir);
  for (let i = 0; i < 16; i++) {
    const irm = path.join(cur, 'receipts', 'ir_manifest.json');
    const irdir = path.join(cur, 'asm', 'ir');
    if (fs.existsSync(irm) && fs.existsSync(irdir)) return cur;
    const parent = path.dirname(cur);
    if (parent === cur) break;
    cur = parent;
  }
  throw new Error('Could not locate repo root from ' + startDir);
}

function loadJson(p) {
  return JSON.parse(fs.readFileSync(p, 'utf8'));
}

function main() {
  const here = __dirname;
  const repo = findRepoRoot(here);
  const irManifestPath = path.join(repo, 'receipts', 'ir_manifest.json');
  const ir = loadJson(irManifestPath);

  const files = Array.isArray(ir.files) ? ir.files : [];
  const out = {
    schema: 'stunir.node_sample_run.v0',
    variant: 'hosted',
    ir_manifest_sha256: sha256File(irManifestPath),
    ir_files_count: files.length,
    ir_files: files.map(f => ({ file: f.file, sha256: f.sha256, bytes_len: f.bytes_len })),
  };

  process.stdout.write(JSON.stringify(out) + '
');
}

if (require.main === module) {
  main();
}
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument('--variant', required=True, choices=['hosted'])
    ap.add_argument('--ir-manifest', required=True)
    ap.add_argument('--out-root', required=True)
    args = ap.parse_args()

    _ = load_ir_manifest(Path(args.ir_manifest))

    out_root = Path(args.out_root)
    out_root.mkdir(parents=True, exist_ok=True)

    write_text(out_root / 'package.json', gen_package_json())
    write_text(out_root / 'index.js', gen_index_js())

    readme = """# STUNIR Node.js target (hosted)

This directory is generated.

- `index.js` prints a deterministic JSON summary derived from `receipts/ir_manifest.json`.
- `package.json` includes a `start` script for convenience.

Run (from repo root):
- `node asm/node/app/index.js`
"""
    write_text(out_root / 'README.md', readme)


if __name__ == '__main__':
    main()
