#!/usr/bin/env python3
"""Emit deterministic .NET hosted-runtime artifacts from the IR manifest.

V0 semantics: introspection/stub.
"""

import argparse
import json
from pathlib import Path


def load_ir_manifest(path: Path) -> dict:
    obj = json.loads(path.read_text(encoding='utf-8'))
    if not isinstance(obj, dict) or obj.get('schema') not in ('stunir.ir_manifest.v2',):
        raise SystemExit(f'Unexpected IR manifest schema in {path}: {obj.get("schema")!r}')
    return obj


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding='utf-8', newline='
')


def gen_csproj() -> str:
    return """<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
"""


def gen_program_cs() -> str:
    return """// Generated by STUNIR (dotnet backend, v0)

using System;
using System.IO;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

static string Sha256File(string p)
{
    using var sha = SHA256.Create();
    var b = File.ReadAllBytes(p);
    var d = sha.ComputeHash(b);
    var sb = new StringBuilder();
    foreach (var x in d) sb.Append(x.ToString("x2"));
    return sb.ToString();
}

static string FindRepoRoot(string startDir)
{
    var cur = Path.GetFullPath(startDir);
    for (int i = 0; i < 16; i++)
    {
        var irm = Path.Combine(cur, "receipts", "ir_manifest.json");
        var irdir = Path.Combine(cur, "asm", "ir");
        if (File.Exists(irm) && Directory.Exists(irdir)) return cur;
        var parent = Directory.GetParent(cur);
        if (parent == null) break;
        cur = parent.FullName;
    }
    throw new Exception("Could not locate repo root from " + startDir);
}

var repo = FindRepoRoot(Directory.GetCurrentDirectory());
var irManifest = Path.Combine(repo, "receipts", "ir_manifest.json");
var sha = Sha256File(irManifest);
var bytesLen = new FileInfo(irManifest).Length;

var outObj = new
{
    schema = "stunir.dotnet_sample_run.v0",
    variant = "hosted",
    ir_manifest_sha256 = sha,
    ir_manifest_bytes_len = bytesLen,
};

var json = JsonSerializer.Serialize(outObj);
Console.WriteLine(json);
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument('--variant', required=True, choices=['hosted'])
    ap.add_argument('--ir-manifest', required=True)
    ap.add_argument('--out-root', required=True)
    args = ap.parse_args()

    _ = load_ir_manifest(Path(args.ir_manifest))

    out_root = Path(args.out_root)
    out_root.mkdir(parents=True, exist_ok=True)

    write_text(out_root / 'StunirApp.csproj', gen_csproj())
    write_text(out_root / 'Program.cs', gen_program_cs())

    readme = """# STUNIR .NET target (hosted)

This directory is generated.

- `Program.cs` prints a deterministic JSON summary bound to `receipts/ir_manifest.json`.

Run (from repo root):
- `dotnet run --project asm/dotnet/app`
"""
    write_text(out_root / 'README.md', readme)


if __name__ == '__main__':
    main()
