#!/usr/bin/env python3
# STUNIR: Refined Rust Generator
# Features: Cargo.toml, src/main.rs
from __future__ import annotations
import argparse, json
from pathlib import Path

def _w(p: Path, s: str) -> None:
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(s, encoding="utf-8", newline="\n")

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--variant", required=True)
    ap.add_argument("--ir-manifest", required=True)
    ap.add_argument("--out-root", required=True)
    args = ap.parse_args()

    out_root = Path(args.out_root)
    ir = json.loads(Path(args.ir_manifest).read_text(encoding="utf-8"))

    # 1. Scaffolding
    _w(out_root / "Cargo.toml", """[package]
name = "stunir_generated"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0"
""")

    # 2. Modules
    src_dir = out_root / "src"
    src_dir.mkdir(parents=True, exist_ok=True)

    modules = ir.get("modules", [])

    if not modules:
        _w(src_dir / "main.rs", 'fn main() { println!("Hello from Refined Rust (No Modules)"); }')
    else:
        # Strategy: Write modules as files, mod.rs or lib.rs
        # For now, simple main.rs aggregation
        mod_decls = []
        for mod in modules:
            name = mod.get("name", "mod")
            code = mod.get("code", "// Empty")
            _w(src_dir / f"{name}.rs", code)
            mod_decls.append(f"mod {name};")

        main_code = "\n".join(mod_decls) + '\nfn main() { println!("STUNIR Rust Artifact Loaded"); }'
        _w(src_dir / "main.rs", main_code)

    _w(out_root / "README.md", "# Rust Artifact\nGenerated by STUNIR Refined Generator")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
