#!/usr/bin/env python3
"""Emit deterministic Ruby hosted-runtime artifacts from the IR manifest.

V0 semantics: introspection/stub.
"""

import argparse
import json
from pathlib import Path


def load_ir_manifest(path: Path) -> dict:
    obj = json.loads(path.read_text(encoding='utf-8'))
    if not isinstance(obj, dict) or obj.get('schema') not in ('stunir.ir_manifest.v2',):
        raise SystemExit(f'Unexpected IR manifest schema in {path}: {obj.get("schema")!r}')
    return obj


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding='utf-8', newline='
')


def gen_main_rb() -> str:
    return """# Generated by STUNIR (ruby backend, v0)

require 'json'
require 'digest'

def sha256_file(p)
  Digest::SHA256.file(p).hexdigest
end

def find_repo_root(start)
  cur = File.expand_path(start)
  16.times do
    irm = File.join(cur, 'receipts', 'ir_manifest.json')
    irdir = File.join(cur, 'asm', 'ir')
    return cur if File.exist?(irm) && Dir.exist?(irdir)
    parent = File.expand_path('..', cur)
    break if parent == cur
    cur = parent
  end
  raise "Could not locate repo root from #{start}"
end

repo = find_repo_root(File.dirname(__FILE__))
ir_manifest_path = File.join(repo, 'receipts', 'ir_manifest.json')
ir = JSON.parse(File.read(ir_manifest_path, encoding: 'UTF-8'))
files = ir['files'].is_a?(Array) ? ir['files'] : []

out = {
  'schema' => 'stunir.ruby_sample_run.v0',
  'variant' => 'hosted',
  'ir_manifest_sha256' => sha256_file(ir_manifest_path),
  'ir_files_count' => files.length,
  'ir_files' => files.map { |f| { 'file' => f['file'], 'sha256' => f['sha256'], 'bytes_len' => f['bytes_len'] } },
}

puts JSON.generate(out)
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument('--variant', required=True, choices=['hosted'])
    ap.add_argument('--ir-manifest', required=True)
    ap.add_argument('--out-root', required=True)
    args = ap.parse_args()

    _ = load_ir_manifest(Path(args.ir_manifest))

    out_root = Path(args.out_root)
    out_root.mkdir(parents=True, exist_ok=True)

    write_text(out_root / 'main.rb', gen_main_rb())

    readme = """# STUNIR Ruby target (hosted)

This directory is generated.

- `main.rb` prints a deterministic JSON summary derived from `receipts/ir_manifest.json`.

Run (from repo root):
- `ruby asm/ruby/app/main.rb`
"""
    write_text(out_root / 'README.md', readme)


if __name__ == '__main__':
    main()
