#!/usr/bin/env python3
"""Generate refined Node.js outputs from IR manifests."""

from __future__ import annotations
import argparse, json
from pathlib import Path

def _w(p: Path, s: str) -> None:
    """Write text to a file path, creating parent directories as needed."""
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(s, encoding="utf-8", newline="\n")

def main() -> int:
    """Read an IR manifest and emit Node.js files and scaffolding."""
    ap = argparse.ArgumentParser()
    ap.add_argument("--variant", required=True)
    ap.add_argument("--ir-manifest", required=True)
    ap.add_argument("--out-root", required=True)
    args = ap.parse_args()

    out_root = Path(args.out_root)
    ir = json.loads(Path(args.ir_manifest).read_text(encoding="utf-8"))

    # 1. Scaffolding
    _w(out_root / "package.json", json.dumps({
        "name": "stunir-generated",
        "version": "0.1.0",
        "type": "module",
        "main": "index.js"
    }, indent=2))

    # 2. Modules
    modules = ir.get("modules", [])
    exports = []

    if not modules:
        _w(out_root / "index.js", "console.log('Hello from Refined Node (No Modules)');")
    else:
        for mod in modules:
            name = mod.get("name", "mod")
            code = mod.get("code", f"// Code for {name}")
            filename = f"{name}.js"
            _w(out_root / filename, code)
            exports.append(f"import './{filename}';")

        _w(out_root / "index.js", "\n".join(exports))

    _w(out_root / "README.md", "# Node.js Artifact\nGenerated by STUNIR Refined Generator")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
