/**
 * STUNIR Provenance Emitter
 * Issue: provenance/1401 - Standardized C Provenance Template
 * 
 * Outputs build provenance information in various formats.
 * Compiled with provenance.h generated by stunir-native gen-provenance.
 */

#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include "provenance.h"

/* Provide fallback definitions if header is incomplete */
#ifndef STUNIR_PROV_BUILD_EPOCH
#define STUNIR_PROV_BUILD_EPOCH 0
#warning "STUNIR_PROV_BUILD_EPOCH not defined, using default"
#endif

#ifndef STUNIR_PROV_SPEC_DIGEST
#define STUNIR_PROV_SPEC_DIGEST "(unknown)"
#warning "STUNIR_PROV_SPEC_DIGEST not defined, using placeholder"
#endif

#ifndef STUNIR_PROV_ASM_DIGEST
#define STUNIR_PROV_ASM_DIGEST "(pending)"
#endif

#ifndef STUNIR_PROV_MODULE_COUNT
#define STUNIR_PROV_MODULE_COUNT 0
#endif

#ifndef STUNIR_PROV_SCHEMA
#define STUNIR_PROV_SCHEMA "stunir.provenance.v1"
#endif

/* Legacy compatibility */
#ifndef _STUNIR_BUILD_EPOCH
#define _STUNIR_BUILD_EPOCH STUNIR_PROV_BUILD_EPOCH
#endif

#define PROV_EMIT_VERSION "1.1.0"

static void print_usage(const char *prog) {
    fprintf(stderr, "Usage: %s [--json | --shell | --help | --version]\n", prog);
    fprintf(stderr, "  --json    Output in JSON format\n");
    fprintf(stderr, "  --shell   Output as shell variables (default)\n");
    fprintf(stderr, "  --version Print version and exit\n");
    fprintf(stderr, "  --help    Show this help\n");
}

static void print_json(void) {
    printf("{\n");
    printf("  \"schema\": \"%s\",\n", STUNIR_PROV_SCHEMA);
    printf("  \"build_epoch\": %lld,\n", (long long)STUNIR_PROV_BUILD_EPOCH);
    printf("  \"spec_digest\": \"%s\",\n", STUNIR_PROV_SPEC_DIGEST);
    printf("  \"asm_digest\": \"%s\",\n", STUNIR_PROV_ASM_DIGEST);
    printf("  \"module_count\": %d\n", STUNIR_PROV_MODULE_COUNT);
    printf("}\n");
}

static void print_shell(void) {
    printf("STUNIR_PROV_SCHEMA='%s'\n", STUNIR_PROV_SCHEMA);
    printf("STUNIR_PROV_BUILD_EPOCH=%lld\n", (long long)STUNIR_PROV_BUILD_EPOCH);
    printf("STUNIR_PROV_SPEC_DIGEST='%s'\n", STUNIR_PROV_SPEC_DIGEST);
    printf("STUNIR_PROV_ASM_DIGEST='%s'\n", STUNIR_PROV_ASM_DIGEST);
    printf("STUNIR_PROV_MODULE_COUNT=%d\n", STUNIR_PROV_MODULE_COUNT);
    /* Legacy format */
    printf("build_epoch=%lld\n", (long long)STUNIR_PROV_BUILD_EPOCH);
    printf("selected_epoch=%lld\n", (long long)_STUNIR_BUILD_EPOCH);
    printf("spec_digest=%s\n", STUNIR_PROV_SPEC_DIGEST);
    printf("asm_digest=%s\n", STUNIR_PROV_ASM_DIGEST);
}

int main(int argc, char *argv[]) {
    if (argc > 1) {
        if (strcmp(argv[1], "--json") == 0) {
            print_json();
            return 0;
        } else if (strcmp(argv[1], "--shell") == 0) {
            print_shell();
            return 0;
        } else if (strcmp(argv[1], "--version") == 0) {
            printf("prov_emit %s\n", PROV_EMIT_VERSION);
            return 0;
        } else if (strcmp(argv[1], "--help") == 0) {
            print_usage(argv[0]);
            return 0;
        } else {
            fprintf(stderr, "Unknown option: %s\n", argv[1]);
            print_usage(argv[0]);
            return 1;
        }
    }
    
    /* Default: shell format */
    print_shell();
    return 0;
}
