/* STUNIR Generated Code
 * Generated by: stunir_ir_to_code_spark v0.2.0
 * Module: control_flow_test
 */

#include <stdint.h>
#include <stdbool.h>

int32_t test_if_then(int32_t x) {
  uint8_t result = 0;
  if (x > 10) {
    result = x * 2;
    result = result + 1;
  }
  return result;

}

int32_t test_if_else(int32_t x) {
  uint8_t result = 0;
  if (x > 0) {
    result = x + 10;
  } else {
    result = -1;
  }
  return result;

}

int32_t test_while_loop(int32_t n) {
  uint8_t sum = 0;
  uint8_t i = 0;
  while (i < n) {
    sum = sum + i;
    i = i + 1;
  }
  return sum;

}

int32_t test_for_loop(int32_t max) {
  uint8_t total = 0;
  for (i = 0; i < max; i++) {
    total = total + (i * 2);
  }
  return total;

}

int32_t test_multiple_if(int32_t a, int32_t b) {
  uint8_t result = 0;
  if (a > 0) {
    result = result + a;
  }
  if (b > 0) {
    result = result + b;
  }
  return result;

}

int32_t test_complex_condition(int32_t x, int32_t y) {
  uint8_t a = 0;
  uint8_t b = 0;
  if (x > y) {
    a = x;
    b = y;
    a = a - b;
  } else {
    a = y;
    b = x;
    a = a - b;
  }
  return a;

}

