--  STUNIR ExpertSystems Emitter - Ada SPARK Specification
--  Expert system rule emitter (CLIPS, Jess, Drools)
--  DO-178C Level A compliant
--  Generated by: STUNIR Emitter Generator v1.0
--  Timestamp: 2026-01-31T02:44:17.970486Z

pragma SPARK_Mode (On);

with Emitter_Types; use Emitter_Types;

package ExpertSystems_Emitter is

   --  ExpertSystems target configuration
   type ExpertSystems_Config is record
      Engine : String;
      Strategy : String;
      Use_Templates : Boolean;
   end record;

   --  Default configuration
   Default_Config : constant ExpertSystems_Config := (
      Engine => clips,
      Strategy => depth,
      Use_Templates => True
   );

   --  Main emission procedure with SPARK contracts
   procedure Emit_Module (
      Name      : in Identifier_String;
      Content   : out Content_String;
      Config    : in ExpertSystems_Config;
      Status    : out Emitter_Status)
      with Pre => Identifier_Strings.Length (Name) > 0,
           Post => (Status = Success) = (Content_Strings.Length (Content) > 0);

   --  Emit function code
   procedure Emit_Function (
      Func_Name : in Identifier_String;
      Params    : in String;
      Body_Code : in String;
      Content   : out Content_String;
      Status    : out Emitter_Status)
      with Pre => Identifier_Strings.Length (Func_Name) > 0;

   --  Type mapping from IR to ExpertSystems
   function Map_Type_To_EXPERT_SYSTEMS (IR_Type : IR_Data_Type) return Type_Name_String;

end ExpertSystems_Emitter;
