/* STUNIR Generated Code (manually corrected for testing)
 * Generated by: stunir_ir_to_code_spark v0.7.1
 * Module: single_level_control_flow_test
 */

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>

int32_t test_simple_if(int32_t x) {
  if (x > 0) {
    return 1;
  } else {
    return 0;
  }
}

int32_t test_simple_while(int32_t n) {
  int32_t i = 0;
  int32_t sum = 0;
  while (i < n) {
    sum = sum + i;
    i = i + 1;
  }
  return sum;
}

int32_t test_simple_for(int32_t max) {
  int32_t product = 1;
  int32_t i;
  for (i = 0; i < max; i = i + 1) {
    product = product * i;
  }
  return product;
}

int main() {
  printf("test_simple_if(5) = %d (expected: 1)\n", test_simple_if(5));
  printf("test_simple_if(-3) = %d (expected: 0)\n", test_simple_if(-3));
  printf("test_simple_while(5) = %d (expected: 10)\n", test_simple_while(5));
  printf("test_simple_for(5) = %d (expected: 0)\n", test_simple_for(5));
  return 0;
}
