/* STUNIR Generated Code
 * Generated by: stunir_ir_to_code_spark v0.7.1
 * Module: single_level_control_flow_test
 */

#include <stdint.h>
#include <stdbool.h>

int32_t test_simple_if(int32_t x) {
  if (x > 0) {
  return 1;
  return 0;
  } else {
  return 0;
  }
  return 0;
}

int32_t test_simple_while(int32_t n) {
  uint8_t i = 0;
  uint8_t sum = 0;
  while (i < n) {
  int32_t sum = sum + i;
  int32_t i = i + 1;
  }
  return sum;

}

int32_t test_simple_for(int32_t max) {
  uint8_t product = 1;
  for (i = 0; i < max; i = i + 1) {
  int32_t product = product * i;
  }
  return product;

}

