use crate::errors::StunirError;
use crate::ir_v1::IrV1;
use anyhow::Result;
use std::fs;
use std::path::Path;

pub fn emit(ir: &IrV1, out_file: &str) -> Result<()> {
    let mut code = String::new();

    code.push_str("# Generated by STUNIR Native Core\n");
    code.push_str("# Target: PowerShell (Windows Shell Primary)\n\n");

    code.push_str("Set-StrictMode -Version Latest\n");
    code.push_str("$ErrorActionPreference = 'Stop'\n\n");

    for func in &ir.functions {
        code.push_str(&format!("function {} {{\n", func.name));
        if func.body.is_empty() {
            code.push_str("    # pass\n");
        } else {
            for instr in &func.body {
                match instr.op.as_str() {
                    "print" => {
                        let args = instr.args.iter()
                            .map(|s| format!("\"{}\"", s))
                            .collect::<Vec<_>>()
                            .join(", ");
                        code.push_str(&format!("    Write-Output {}\n", args));
                    }
                    _ => {
                        code.push_str(&format!("    # Unknown Op: {}\n", instr.op));
                    }
                }
            }
        }
        code.push_str("}\n\n");
    }

    code.push_str("# Entry Point\n");
    code.push_str("if ($MyInvocation.MyCommandType -eq 'ExternalScript') {\n");
    code.push_str("    main\n");
    code.push_str("}\n");

    if let Some(parent) = Path::new(out_file).parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(out_file, code)
        .map_err(|e| StunirError::Io(format!("Failed to write PowerShell file: {}", e)).into())
}
