use crate::errors::StunirError;
use crate::ir_v1::IrV1;
use anyhow::Result;
use std::fs;
use std::path::Path;

pub fn emit(ir: &IrV1, out_file: &str) -> Result<()> {
    let mut code = String::new();

    code.push_str("# Generated by STUNIR Native Core (Rust)\n");
    code.push_str("# Target: Python\n\n");

    for func in &ir.functions {
        code.push_str(&format!("def {}():\n", func.name));
        if func.body.is_empty() {
            code.push_str("    pass\n");
        } else {
            for instr in &func.body {
                match instr.op.as_str() {
                    "print" => {
                        let args = instr.args.iter()
                            .map(|s| format!("\"{}\"", s))
                            .collect::<Vec<_>>()
                            .join(", ");
                        code.push_str(&format!("    print({})\n", args));
                    }
                    _ => {
                        code.push_str(&format!("    # Unknown Op: {}\n", instr.op));
                    }
                }
            }
        }
        code.push_str("\n");
    }

    code.push_str("if __name__ == \"__main__\":\n");
    code.push_str("    main()\n");

    if let Some(parent) = Path::new(out_file).parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(out_file, code)
        .map_err(|e| StunirError::Io(format!("Failed to write Python file: {}", e)).into())
}
