use crate::errors::StunirError;
use crate::ir_v1::IrV1;
use anyhow::Result;
use std::fs;
use std::path::Path;
use std::collections::HashMap;

pub fn emit(ir: &IrV1, out_file: &str) -> Result<()> {
    let mut code = String::new();
    let mut data_section = String::new();
    let mut string_offset = 0;
    let mut string_map: HashMap<String, (i32, i32)> = HashMap::new();

    // Header
    code.push_str("(module\n");
    code.push_str("  ;; Generated by STUNIR Native Core\n");
    code.push_str("  ;; Target: WebAssembly Text (WAT)\n\n");

    // Imports (We need a host environment to print)
    code.push_str("  ;; Import 'print' from host environment (pointer, length)\n");
    code.push_str("  (import \"env\" \"print\" (func $print (param i32 i32)))\n\n");

    // Memory (1 page = 64KB)
    code.push_str("  (memory 1)\n");
    code.push_str("  (export \"memory\" (memory 0))\n\n");

    // Code Generation
    for func in &ir.functions {
        code.push_str(&format!("  (func ${} (export \"{}\")\n", func.name, func.name));

        for instr in &func.body {
            match instr.op.as_str() {
                "print" => {
                    for arg in &instr.args {
                        // 1. Store string in Data Section if new
                        if !string_map.contains_key(arg) {
                            let len = arg.len() as i32;
                            string_map.insert(arg.clone(), (string_offset, len));

                            // Add to data section: (data (i32.const OFFSET) "STRING")
                            data_section.push_str(&format!("  (data (i32.const {}) \"{}\")\n", string_offset, arg));

                            string_offset += len;
                        }

                        // 2. Generate Instructions to push ptr/len and call
                        let (ptr, len) = string_map[arg];
                        code.push_str(&format!("    ;; print(\"{}\")\n", arg));
                        code.push_str(&format!("    i32.const {}  ;; pointer\n", ptr));
                        code.push_str(&format!("    i32.const {}  ;; length\n", len));
                        code.push_str("    call $print\n");
                    }
                }
                _ => {
                    code.push_str(&format!("    ;; Unknown Op: {}\n", instr.op));
                }
            }
        }
        code.push_str("  )\n");
    }

    // Append Data Section at the end
    code.push_str("\n  ;; Data Section\n");
    code.push_str(&data_section);

    code.push_str(")\n");

    if let Some(parent) = Path::new(out_file).parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(out_file, code)
        .map_err(|e| StunirError::Io(format!("Failed to write WAT file: {}", e)).into())
}
